// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: fog.proto

package gazebo.msgs;

public final class GzFog {
  private GzFog() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface FogOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .gazebo.msgs.Fog.FogType type = 1;
    /**
     * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
     */
    boolean hasType();
    /**
     * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
     */
    gazebo.msgs.GzFog.Fog.FogType getType();

    // optional .gazebo.msgs.Color color = 2;
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    boolean hasColor();
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    gazebo.msgs.GzColor.Color getColor();
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    gazebo.msgs.GzColor.ColorOrBuilder getColorOrBuilder();

    // optional float density = 3;
    /**
     * <code>optional float density = 3;</code>
     */
    boolean hasDensity();
    /**
     * <code>optional float density = 3;</code>
     */
    float getDensity();

    // optional float start = 4;
    /**
     * <code>optional float start = 4;</code>
     */
    boolean hasStart();
    /**
     * <code>optional float start = 4;</code>
     */
    float getStart();

    // optional float end = 5;
    /**
     * <code>optional float end = 5;</code>
     */
    boolean hasEnd();
    /**
     * <code>optional float end = 5;</code>
     */
    float getEnd();
  }
  /**
   * Protobuf type {@code gazebo.msgs.Fog}
   */
  public static final class Fog extends
      com.google.protobuf.GeneratedMessage
      implements FogOrBuilder {
    // Use Fog.newBuilder() to construct.
    private Fog(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Fog(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Fog defaultInstance;
    public static Fog getDefaultInstance() {
      return defaultInstance;
    }

    public Fog getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Fog(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              gazebo.msgs.GzFog.Fog.FogType value = gazebo.msgs.GzFog.Fog.FogType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                type_ = value;
              }
              break;
            }
            case 18: {
              gazebo.msgs.GzColor.Color.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = color_.toBuilder();
              }
              color_ = input.readMessage(gazebo.msgs.GzColor.Color.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(color_);
                color_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
            case 29: {
              bitField0_ |= 0x00000004;
              density_ = input.readFloat();
              break;
            }
            case 37: {
              bitField0_ |= 0x00000008;
              start_ = input.readFloat();
              break;
            }
            case 45: {
              bitField0_ |= 0x00000010;
              end_ = input.readFloat();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.GzFog.internal_static_gazebo_msgs_Fog_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.GzFog.internal_static_gazebo_msgs_Fog_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.GzFog.Fog.class, gazebo.msgs.GzFog.Fog.Builder.class);
    }

    public static com.google.protobuf.Parser<Fog> PARSER =
        new com.google.protobuf.AbstractParser<Fog>() {
      public Fog parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Fog(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Fog> getParserForType() {
      return PARSER;
    }

    /**
     * Protobuf enum {@code gazebo.msgs.Fog.FogType}
     */
    public enum FogType
        implements com.google.protobuf.ProtocolMessageEnum {
      /**
       * <code>NONE = 1;</code>
       */
      NONE(0, 1),
      /**
       * <code>LINEAR = 2;</code>
       */
      LINEAR(1, 2),
      /**
       * <code>EXPONENTIAL = 3;</code>
       */
      EXPONENTIAL(2, 3),
      /**
       * <code>EXPONENTIAL2 = 4;</code>
       */
      EXPONENTIAL2(3, 4),
      ;

      /**
       * <code>NONE = 1;</code>
       */
      public static final int NONE_VALUE = 1;
      /**
       * <code>LINEAR = 2;</code>
       */
      public static final int LINEAR_VALUE = 2;
      /**
       * <code>EXPONENTIAL = 3;</code>
       */
      public static final int EXPONENTIAL_VALUE = 3;
      /**
       * <code>EXPONENTIAL2 = 4;</code>
       */
      public static final int EXPONENTIAL2_VALUE = 4;


      public final int getNumber() { return value; }

      public static FogType valueOf(int value) {
        switch (value) {
          case 1: return NONE;
          case 2: return LINEAR;
          case 3: return EXPONENTIAL;
          case 4: return EXPONENTIAL2;
          default: return null;
        }
      }

      public static com.google.protobuf.Internal.EnumLiteMap<FogType>
          internalGetValueMap() {
        return internalValueMap;
      }
      private static com.google.protobuf.Internal.EnumLiteMap<FogType>
          internalValueMap =
            new com.google.protobuf.Internal.EnumLiteMap<FogType>() {
              public FogType findValueByNumber(int number) {
                return FogType.valueOf(number);
              }
            };

      public final com.google.protobuf.Descriptors.EnumValueDescriptor
          getValueDescriptor() {
        return getDescriptor().getValues().get(index);
      }
      public final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptorForType() {
        return getDescriptor();
      }
      public static final com.google.protobuf.Descriptors.EnumDescriptor
          getDescriptor() {
        return gazebo.msgs.GzFog.Fog.getDescriptor().getEnumTypes().get(0);
      }

      private static final FogType[] VALUES = values();

      public static FogType valueOf(
          com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
        if (desc.getType() != getDescriptor()) {
          throw new java.lang.IllegalArgumentException(
            "EnumValueDescriptor is not for this type.");
        }
        return VALUES[desc.getIndex()];
      }

      private final int index;
      private final int value;

      private FogType(int index, int value) {
        this.index = index;
        this.value = value;
      }

      // @@protoc_insertion_point(enum_scope:gazebo.msgs.Fog.FogType)
    }

    private int bitField0_;
    // optional .gazebo.msgs.Fog.FogType type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private gazebo.msgs.GzFog.Fog.FogType type_;
    /**
     * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
     */
    public boolean hasType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
     */
    public gazebo.msgs.GzFog.Fog.FogType getType() {
      return type_;
    }

    // optional .gazebo.msgs.Color color = 2;
    public static final int COLOR_FIELD_NUMBER = 2;
    private gazebo.msgs.GzColor.Color color_;
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    public boolean hasColor() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    public gazebo.msgs.GzColor.Color getColor() {
      return color_;
    }
    /**
     * <code>optional .gazebo.msgs.Color color = 2;</code>
     */
    public gazebo.msgs.GzColor.ColorOrBuilder getColorOrBuilder() {
      return color_;
    }

    // optional float density = 3;
    public static final int DENSITY_FIELD_NUMBER = 3;
    private float density_;
    /**
     * <code>optional float density = 3;</code>
     */
    public boolean hasDensity() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional float density = 3;</code>
     */
    public float getDensity() {
      return density_;
    }

    // optional float start = 4;
    public static final int START_FIELD_NUMBER = 4;
    private float start_;
    /**
     * <code>optional float start = 4;</code>
     */
    public boolean hasStart() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional float start = 4;</code>
     */
    public float getStart() {
      return start_;
    }

    // optional float end = 5;
    public static final int END_FIELD_NUMBER = 5;
    private float end_;
    /**
     * <code>optional float end = 5;</code>
     */
    public boolean hasEnd() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional float end = 5;</code>
     */
    public float getEnd() {
      return end_;
    }

    private void initFields() {
      type_ = gazebo.msgs.GzFog.Fog.FogType.NONE;
      color_ = gazebo.msgs.GzColor.Color.getDefaultInstance();
      density_ = 0F;
      start_ = 0F;
      end_ = 0F;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasColor()) {
        if (!getColor().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeFloat(3, density_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeFloat(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeFloat(5, end_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, type_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, color_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, density_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, start_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(5, end_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gazebo.msgs.GzFog.Fog parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzFog.Fog parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gazebo.msgs.GzFog.Fog parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzFog.Fog parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gazebo.msgs.GzFog.Fog prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.Fog}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gazebo.msgs.GzFog.FogOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzFog.internal_static_gazebo_msgs_Fog_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzFog.internal_static_gazebo_msgs_Fog_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzFog.Fog.class, gazebo.msgs.GzFog.Fog.Builder.class);
      }

      // Construct using gazebo.msgs.GzFog.Fog.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getColorFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        type_ = gazebo.msgs.GzFog.Fog.FogType.NONE;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (colorBuilder_ == null) {
          color_ = gazebo.msgs.GzColor.Color.getDefaultInstance();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        density_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000004);
        start_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000008);
        end_ = 0F;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.GzFog.internal_static_gazebo_msgs_Fog_descriptor;
      }

      public gazebo.msgs.GzFog.Fog getDefaultInstanceForType() {
        return gazebo.msgs.GzFog.Fog.getDefaultInstance();
      }

      public gazebo.msgs.GzFog.Fog build() {
        gazebo.msgs.GzFog.Fog result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gazebo.msgs.GzFog.Fog buildPartial() {
        gazebo.msgs.GzFog.Fog result = new gazebo.msgs.GzFog.Fog(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.type_ = type_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (colorBuilder_ == null) {
          result.color_ = color_;
        } else {
          result.color_ = colorBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.density_ = density_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.start_ = start_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.end_ = end_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.GzFog.Fog) {
          return mergeFrom((gazebo.msgs.GzFog.Fog)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.GzFog.Fog other) {
        if (other == gazebo.msgs.GzFog.Fog.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasColor()) {
          mergeColor(other.getColor());
        }
        if (other.hasDensity()) {
          setDensity(other.getDensity());
        }
        if (other.hasStart()) {
          setStart(other.getStart());
        }
        if (other.hasEnd()) {
          setEnd(other.getEnd());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasColor()) {
          if (!getColor().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.GzFog.Fog parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.GzFog.Fog) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .gazebo.msgs.Fog.FogType type = 1;
      private gazebo.msgs.GzFog.Fog.FogType type_ = gazebo.msgs.GzFog.Fog.FogType.NONE;
      /**
       * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
       */
      public boolean hasType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
       */
      public gazebo.msgs.GzFog.Fog.FogType getType() {
        return type_;
      }
      /**
       * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
       */
      public Builder setType(gazebo.msgs.GzFog.Fog.FogType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        type_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Fog.FogType type = 1;</code>
       */
      public Builder clearType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        type_ = gazebo.msgs.GzFog.Fog.FogType.NONE;
        onChanged();
        return this;
      }

      // optional .gazebo.msgs.Color color = 2;
      private gazebo.msgs.GzColor.Color color_ = gazebo.msgs.GzColor.Color.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzColor.Color, gazebo.msgs.GzColor.Color.Builder, gazebo.msgs.GzColor.ColorOrBuilder> colorBuilder_;
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public boolean hasColor() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public gazebo.msgs.GzColor.Color getColor() {
        if (colorBuilder_ == null) {
          return color_;
        } else {
          return colorBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public Builder setColor(gazebo.msgs.GzColor.Color value) {
        if (colorBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          color_ = value;
          onChanged();
        } else {
          colorBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public Builder setColor(
          gazebo.msgs.GzColor.Color.Builder builderForValue) {
        if (colorBuilder_ == null) {
          color_ = builderForValue.build();
          onChanged();
        } else {
          colorBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public Builder mergeColor(gazebo.msgs.GzColor.Color value) {
        if (colorBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              color_ != gazebo.msgs.GzColor.Color.getDefaultInstance()) {
            color_ =
              gazebo.msgs.GzColor.Color.newBuilder(color_).mergeFrom(value).buildPartial();
          } else {
            color_ = value;
          }
          onChanged();
        } else {
          colorBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public Builder clearColor() {
        if (colorBuilder_ == null) {
          color_ = gazebo.msgs.GzColor.Color.getDefaultInstance();
          onChanged();
        } else {
          colorBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public gazebo.msgs.GzColor.Color.Builder getColorBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getColorFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      public gazebo.msgs.GzColor.ColorOrBuilder getColorOrBuilder() {
        if (colorBuilder_ != null) {
          return colorBuilder_.getMessageOrBuilder();
        } else {
          return color_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.Color color = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzColor.Color, gazebo.msgs.GzColor.Color.Builder, gazebo.msgs.GzColor.ColorOrBuilder> 
          getColorFieldBuilder() {
        if (colorBuilder_ == null) {
          colorBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzColor.Color, gazebo.msgs.GzColor.Color.Builder, gazebo.msgs.GzColor.ColorOrBuilder>(
                  color_,
                  getParentForChildren(),
                  isClean());
          color_ = null;
        }
        return colorBuilder_;
      }

      // optional float density = 3;
      private float density_ ;
      /**
       * <code>optional float density = 3;</code>
       */
      public boolean hasDensity() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional float density = 3;</code>
       */
      public float getDensity() {
        return density_;
      }
      /**
       * <code>optional float density = 3;</code>
       */
      public Builder setDensity(float value) {
        bitField0_ |= 0x00000004;
        density_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float density = 3;</code>
       */
      public Builder clearDensity() {
        bitField0_ = (bitField0_ & ~0x00000004);
        density_ = 0F;
        onChanged();
        return this;
      }

      // optional float start = 4;
      private float start_ ;
      /**
       * <code>optional float start = 4;</code>
       */
      public boolean hasStart() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float start = 4;</code>
       */
      public float getStart() {
        return start_;
      }
      /**
       * <code>optional float start = 4;</code>
       */
      public Builder setStart(float value) {
        bitField0_ |= 0x00000008;
        start_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float start = 4;</code>
       */
      public Builder clearStart() {
        bitField0_ = (bitField0_ & ~0x00000008);
        start_ = 0F;
        onChanged();
        return this;
      }

      // optional float end = 5;
      private float end_ ;
      /**
       * <code>optional float end = 5;</code>
       */
      public boolean hasEnd() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional float end = 5;</code>
       */
      public float getEnd() {
        return end_;
      }
      /**
       * <code>optional float end = 5;</code>
       */
      public Builder setEnd(float value) {
        bitField0_ |= 0x00000010;
        end_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional float end = 5;</code>
       */
      public Builder clearEnd() {
        bitField0_ = (bitField0_ & ~0x00000010);
        end_ = 0F;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.Fog)
    }

    static {
      defaultInstance = new Fog(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.Fog)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Fog_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_Fog_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\tfog.proto\022\013gazebo.msgs\032\013color.proto\"\301\001" +
      "\n\003Fog\022&\n\004type\030\001 \001(\0162\030.gazebo.msgs.Fog.Fo" +
      "gType\022!\n\005color\030\002 \001(\0132\022.gazebo.msgs.Color" +
      "\022\017\n\007density\030\003 \001(\002\022\r\n\005start\030\004 \001(\002\022\013\n\003end\030" +
      "\005 \001(\002\"B\n\007FogType\022\010\n\004NONE\020\001\022\n\n\006LINEAR\020\002\022\017" +
      "\n\013EXPONENTIAL\020\003\022\020\n\014EXPONENTIAL2\020\004B\007B\005GzF" +
      "og"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gazebo_msgs_Fog_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gazebo_msgs_Fog_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_Fog_descriptor,
              new java.lang.String[] { "Type", "Color", "Density", "Start", "End", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GzColor.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
