// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: joint_wrench.proto

package gazebo.msgs;

public final class GzJointWrench {
  private GzJointWrench() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface JointWrenchOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string body_1_name = 1;
    /**
     * <code>required string body_1_name = 1;</code>
     */
    boolean hasBody1Name();
    /**
     * <code>required string body_1_name = 1;</code>
     */
    java.lang.String getBody1Name();
    /**
     * <code>required string body_1_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getBody1NameBytes();

    // required uint32 body_1_id = 2;
    /**
     * <code>required uint32 body_1_id = 2;</code>
     */
    boolean hasBody1Id();
    /**
     * <code>required uint32 body_1_id = 2;</code>
     */
    int getBody1Id();

    // required string body_2_name = 3;
    /**
     * <code>required string body_2_name = 3;</code>
     */
    boolean hasBody2Name();
    /**
     * <code>required string body_2_name = 3;</code>
     */
    java.lang.String getBody2Name();
    /**
     * <code>required string body_2_name = 3;</code>
     */
    com.google.protobuf.ByteString
        getBody2NameBytes();

    // required uint32 body_2_id = 4;
    /**
     * <code>required uint32 body_2_id = 4;</code>
     */
    boolean hasBody2Id();
    /**
     * <code>required uint32 body_2_id = 4;</code>
     */
    int getBody2Id();

    // required .gazebo.msgs.Wrench body_1_wrench = 5;
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    boolean hasBody1Wrench();
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    gazebo.msgs.GzWrench.Wrench getBody1Wrench();
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    gazebo.msgs.GzWrench.WrenchOrBuilder getBody1WrenchOrBuilder();

    // required .gazebo.msgs.Wrench body_2_wrench = 6;
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    boolean hasBody2Wrench();
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    gazebo.msgs.GzWrench.Wrench getBody2Wrench();
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    gazebo.msgs.GzWrench.WrenchOrBuilder getBody2WrenchOrBuilder();
  }
  /**
   * Protobuf type {@code gazebo.msgs.JointWrench}
   */
  public static final class JointWrench extends
      com.google.protobuf.GeneratedMessage
      implements JointWrenchOrBuilder {
    // Use JointWrench.newBuilder() to construct.
    private JointWrench(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private JointWrench(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final JointWrench defaultInstance;
    public static JointWrench getDefaultInstance() {
      return defaultInstance;
    }

    public JointWrench getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private JointWrench(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              body1Name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              body1Id_ = input.readUInt32();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000004;
              body2Name_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              body2Id_ = input.readUInt32();
              break;
            }
            case 42: {
              gazebo.msgs.GzWrench.Wrench.Builder subBuilder = null;
              if (((bitField0_ & 0x00000010) == 0x00000010)) {
                subBuilder = body1Wrench_.toBuilder();
              }
              body1Wrench_ = input.readMessage(gazebo.msgs.GzWrench.Wrench.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body1Wrench_);
                body1Wrench_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000010;
              break;
            }
            case 50: {
              gazebo.msgs.GzWrench.Wrench.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = body2Wrench_.toBuilder();
              }
              body2Wrench_ = input.readMessage(gazebo.msgs.GzWrench.Wrench.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(body2Wrench_);
                body2Wrench_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.GzJointWrench.internal_static_gazebo_msgs_JointWrench_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.GzJointWrench.internal_static_gazebo_msgs_JointWrench_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.GzJointWrench.JointWrench.class, gazebo.msgs.GzJointWrench.JointWrench.Builder.class);
    }

    public static com.google.protobuf.Parser<JointWrench> PARSER =
        new com.google.protobuf.AbstractParser<JointWrench>() {
      public JointWrench parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new JointWrench(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<JointWrench> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string body_1_name = 1;
    public static final int BODY_1_NAME_FIELD_NUMBER = 1;
    private java.lang.Object body1Name_;
    /**
     * <code>required string body_1_name = 1;</code>
     */
    public boolean hasBody1Name() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string body_1_name = 1;</code>
     */
    public java.lang.String getBody1Name() {
      java.lang.Object ref = body1Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body1Name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body_1_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getBody1NameBytes() {
      java.lang.Object ref = body1Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body1Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 body_1_id = 2;
    public static final int BODY_1_ID_FIELD_NUMBER = 2;
    private int body1Id_;
    /**
     * <code>required uint32 body_1_id = 2;</code>
     */
    public boolean hasBody1Id() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required uint32 body_1_id = 2;</code>
     */
    public int getBody1Id() {
      return body1Id_;
    }

    // required string body_2_name = 3;
    public static final int BODY_2_NAME_FIELD_NUMBER = 3;
    private java.lang.Object body2Name_;
    /**
     * <code>required string body_2_name = 3;</code>
     */
    public boolean hasBody2Name() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>required string body_2_name = 3;</code>
     */
    public java.lang.String getBody2Name() {
      java.lang.Object ref = body2Name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          body2Name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string body_2_name = 3;</code>
     */
    public com.google.protobuf.ByteString
        getBody2NameBytes() {
      java.lang.Object ref = body2Name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        body2Name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // required uint32 body_2_id = 4;
    public static final int BODY_2_ID_FIELD_NUMBER = 4;
    private int body2Id_;
    /**
     * <code>required uint32 body_2_id = 4;</code>
     */
    public boolean hasBody2Id() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>required uint32 body_2_id = 4;</code>
     */
    public int getBody2Id() {
      return body2Id_;
    }

    // required .gazebo.msgs.Wrench body_1_wrench = 5;
    public static final int BODY_1_WRENCH_FIELD_NUMBER = 5;
    private gazebo.msgs.GzWrench.Wrench body1Wrench_;
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    public boolean hasBody1Wrench() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    public gazebo.msgs.GzWrench.Wrench getBody1Wrench() {
      return body1Wrench_;
    }
    /**
     * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
     */
    public gazebo.msgs.GzWrench.WrenchOrBuilder getBody1WrenchOrBuilder() {
      return body1Wrench_;
    }

    // required .gazebo.msgs.Wrench body_2_wrench = 6;
    public static final int BODY_2_WRENCH_FIELD_NUMBER = 6;
    private gazebo.msgs.GzWrench.Wrench body2Wrench_;
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    public boolean hasBody2Wrench() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    public gazebo.msgs.GzWrench.Wrench getBody2Wrench() {
      return body2Wrench_;
    }
    /**
     * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
     */
    public gazebo.msgs.GzWrench.WrenchOrBuilder getBody2WrenchOrBuilder() {
      return body2Wrench_;
    }

    private void initFields() {
      body1Name_ = "";
      body1Id_ = 0;
      body2Name_ = "";
      body2Id_ = 0;
      body1Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
      body2Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasBody1Name()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody1Id()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody2Name()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody2Id()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody1Wrench()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasBody2Wrench()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBody1Wrench().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!getBody2Wrench().isInitialized()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getBody1NameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, body1Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBytes(3, getBody2NameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeUInt32(4, body2Id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeMessage(5, body1Wrench_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(6, body2Wrench_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getBody1NameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, body1Id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, getBody2NameBytes());
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(4, body2Id_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, body1Wrench_);
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, body2Wrench_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzJointWrench.JointWrench parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gazebo.msgs.GzJointWrench.JointWrench prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.JointWrench}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gazebo.msgs.GzJointWrench.JointWrenchOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzJointWrench.internal_static_gazebo_msgs_JointWrench_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzJointWrench.internal_static_gazebo_msgs_JointWrench_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzJointWrench.JointWrench.class, gazebo.msgs.GzJointWrench.JointWrench.Builder.class);
      }

      // Construct using gazebo.msgs.GzJointWrench.JointWrench.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getBody1WrenchFieldBuilder();
          getBody2WrenchFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        body1Name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        body1Id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        body2Name_ = "";
        bitField0_ = (bitField0_ & ~0x00000004);
        body2Id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        if (body1WrenchBuilder_ == null) {
          body1Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
        } else {
          body1WrenchBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        if (body2WrenchBuilder_ == null) {
          body2Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
        } else {
          body2WrenchBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.GzJointWrench.internal_static_gazebo_msgs_JointWrench_descriptor;
      }

      public gazebo.msgs.GzJointWrench.JointWrench getDefaultInstanceForType() {
        return gazebo.msgs.GzJointWrench.JointWrench.getDefaultInstance();
      }

      public gazebo.msgs.GzJointWrench.JointWrench build() {
        gazebo.msgs.GzJointWrench.JointWrench result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gazebo.msgs.GzJointWrench.JointWrench buildPartial() {
        gazebo.msgs.GzJointWrench.JointWrench result = new gazebo.msgs.GzJointWrench.JointWrench(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.body1Name_ = body1Name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.body1Id_ = body1Id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.body2Name_ = body2Name_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.body2Id_ = body2Id_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        if (body1WrenchBuilder_ == null) {
          result.body1Wrench_ = body1Wrench_;
        } else {
          result.body1Wrench_ = body1WrenchBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        if (body2WrenchBuilder_ == null) {
          result.body2Wrench_ = body2Wrench_;
        } else {
          result.body2Wrench_ = body2WrenchBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.GzJointWrench.JointWrench) {
          return mergeFrom((gazebo.msgs.GzJointWrench.JointWrench)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.GzJointWrench.JointWrench other) {
        if (other == gazebo.msgs.GzJointWrench.JointWrench.getDefaultInstance()) return this;
        if (other.hasBody1Name()) {
          bitField0_ |= 0x00000001;
          body1Name_ = other.body1Name_;
          onChanged();
        }
        if (other.hasBody1Id()) {
          setBody1Id(other.getBody1Id());
        }
        if (other.hasBody2Name()) {
          bitField0_ |= 0x00000004;
          body2Name_ = other.body2Name_;
          onChanged();
        }
        if (other.hasBody2Id()) {
          setBody2Id(other.getBody2Id());
        }
        if (other.hasBody1Wrench()) {
          mergeBody1Wrench(other.getBody1Wrench());
        }
        if (other.hasBody2Wrench()) {
          mergeBody2Wrench(other.getBody2Wrench());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasBody1Name()) {
          
          return false;
        }
        if (!hasBody1Id()) {
          
          return false;
        }
        if (!hasBody2Name()) {
          
          return false;
        }
        if (!hasBody2Id()) {
          
          return false;
        }
        if (!hasBody1Wrench()) {
          
          return false;
        }
        if (!hasBody2Wrench()) {
          
          return false;
        }
        if (!getBody1Wrench().isInitialized()) {
          
          return false;
        }
        if (!getBody2Wrench().isInitialized()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.GzJointWrench.JointWrench parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.GzJointWrench.JointWrench) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string body_1_name = 1;
      private java.lang.Object body1Name_ = "";
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public boolean hasBody1Name() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public java.lang.String getBody1Name() {
        java.lang.Object ref = body1Name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body1Name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getBody1NameBytes() {
        java.lang.Object ref = body1Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body1Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public Builder setBody1Name(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        body1Name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public Builder clearBody1Name() {
        bitField0_ = (bitField0_ & ~0x00000001);
        body1Name_ = getDefaultInstance().getBody1Name();
        onChanged();
        return this;
      }
      /**
       * <code>required string body_1_name = 1;</code>
       */
      public Builder setBody1NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        body1Name_ = value;
        onChanged();
        return this;
      }

      // required uint32 body_1_id = 2;
      private int body1Id_ ;
      /**
       * <code>required uint32 body_1_id = 2;</code>
       */
      public boolean hasBody1Id() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required uint32 body_1_id = 2;</code>
       */
      public int getBody1Id() {
        return body1Id_;
      }
      /**
       * <code>required uint32 body_1_id = 2;</code>
       */
      public Builder setBody1Id(int value) {
        bitField0_ |= 0x00000002;
        body1Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 body_1_id = 2;</code>
       */
      public Builder clearBody1Id() {
        bitField0_ = (bitField0_ & ~0x00000002);
        body1Id_ = 0;
        onChanged();
        return this;
      }

      // required string body_2_name = 3;
      private java.lang.Object body2Name_ = "";
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public boolean hasBody2Name() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public java.lang.String getBody2Name() {
        java.lang.Object ref = body2Name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          body2Name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public com.google.protobuf.ByteString
          getBody2NameBytes() {
        java.lang.Object ref = body2Name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          body2Name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public Builder setBody2Name(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body2Name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public Builder clearBody2Name() {
        bitField0_ = (bitField0_ & ~0x00000004);
        body2Name_ = getDefaultInstance().getBody2Name();
        onChanged();
        return this;
      }
      /**
       * <code>required string body_2_name = 3;</code>
       */
      public Builder setBody2NameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
        body2Name_ = value;
        onChanged();
        return this;
      }

      // required uint32 body_2_id = 4;
      private int body2Id_ ;
      /**
       * <code>required uint32 body_2_id = 4;</code>
       */
      public boolean hasBody2Id() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>required uint32 body_2_id = 4;</code>
       */
      public int getBody2Id() {
        return body2Id_;
      }
      /**
       * <code>required uint32 body_2_id = 4;</code>
       */
      public Builder setBody2Id(int value) {
        bitField0_ |= 0x00000008;
        body2Id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required uint32 body_2_id = 4;</code>
       */
      public Builder clearBody2Id() {
        bitField0_ = (bitField0_ & ~0x00000008);
        body2Id_ = 0;
        onChanged();
        return this;
      }

      // required .gazebo.msgs.Wrench body_1_wrench = 5;
      private gazebo.msgs.GzWrench.Wrench body1Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder> body1WrenchBuilder_;
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public boolean hasBody1Wrench() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public gazebo.msgs.GzWrench.Wrench getBody1Wrench() {
        if (body1WrenchBuilder_ == null) {
          return body1Wrench_;
        } else {
          return body1WrenchBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public Builder setBody1Wrench(gazebo.msgs.GzWrench.Wrench value) {
        if (body1WrenchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body1Wrench_ = value;
          onChanged();
        } else {
          body1WrenchBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public Builder setBody1Wrench(
          gazebo.msgs.GzWrench.Wrench.Builder builderForValue) {
        if (body1WrenchBuilder_ == null) {
          body1Wrench_ = builderForValue.build();
          onChanged();
        } else {
          body1WrenchBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public Builder mergeBody1Wrench(gazebo.msgs.GzWrench.Wrench value) {
        if (body1WrenchBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010) &&
              body1Wrench_ != gazebo.msgs.GzWrench.Wrench.getDefaultInstance()) {
            body1Wrench_ =
              gazebo.msgs.GzWrench.Wrench.newBuilder(body1Wrench_).mergeFrom(value).buildPartial();
          } else {
            body1Wrench_ = value;
          }
          onChanged();
        } else {
          body1WrenchBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000010;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public Builder clearBody1Wrench() {
        if (body1WrenchBuilder_ == null) {
          body1Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
          onChanged();
        } else {
          body1WrenchBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public gazebo.msgs.GzWrench.Wrench.Builder getBody1WrenchBuilder() {
        bitField0_ |= 0x00000010;
        onChanged();
        return getBody1WrenchFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      public gazebo.msgs.GzWrench.WrenchOrBuilder getBody1WrenchOrBuilder() {
        if (body1WrenchBuilder_ != null) {
          return body1WrenchBuilder_.getMessageOrBuilder();
        } else {
          return body1Wrench_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_1_wrench = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder> 
          getBody1WrenchFieldBuilder() {
        if (body1WrenchBuilder_ == null) {
          body1WrenchBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder>(
                  body1Wrench_,
                  getParentForChildren(),
                  isClean());
          body1Wrench_ = null;
        }
        return body1WrenchBuilder_;
      }

      // required .gazebo.msgs.Wrench body_2_wrench = 6;
      private gazebo.msgs.GzWrench.Wrench body2Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder> body2WrenchBuilder_;
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public boolean hasBody2Wrench() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public gazebo.msgs.GzWrench.Wrench getBody2Wrench() {
        if (body2WrenchBuilder_ == null) {
          return body2Wrench_;
        } else {
          return body2WrenchBuilder_.getMessage();
        }
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public Builder setBody2Wrench(gazebo.msgs.GzWrench.Wrench value) {
        if (body2WrenchBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          body2Wrench_ = value;
          onChanged();
        } else {
          body2WrenchBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public Builder setBody2Wrench(
          gazebo.msgs.GzWrench.Wrench.Builder builderForValue) {
        if (body2WrenchBuilder_ == null) {
          body2Wrench_ = builderForValue.build();
          onChanged();
        } else {
          body2WrenchBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public Builder mergeBody2Wrench(gazebo.msgs.GzWrench.Wrench value) {
        if (body2WrenchBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020) &&
              body2Wrench_ != gazebo.msgs.GzWrench.Wrench.getDefaultInstance()) {
            body2Wrench_ =
              gazebo.msgs.GzWrench.Wrench.newBuilder(body2Wrench_).mergeFrom(value).buildPartial();
          } else {
            body2Wrench_ = value;
          }
          onChanged();
        } else {
          body2WrenchBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000020;
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public Builder clearBody2Wrench() {
        if (body2WrenchBuilder_ == null) {
          body2Wrench_ = gazebo.msgs.GzWrench.Wrench.getDefaultInstance();
          onChanged();
        } else {
          body2WrenchBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000020);
        return this;
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public gazebo.msgs.GzWrench.Wrench.Builder getBody2WrenchBuilder() {
        bitField0_ |= 0x00000020;
        onChanged();
        return getBody2WrenchFieldBuilder().getBuilder();
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      public gazebo.msgs.GzWrench.WrenchOrBuilder getBody2WrenchOrBuilder() {
        if (body2WrenchBuilder_ != null) {
          return body2WrenchBuilder_.getMessageOrBuilder();
        } else {
          return body2Wrench_;
        }
      }
      /**
       * <code>required .gazebo.msgs.Wrench body_2_wrench = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder> 
          getBody2WrenchFieldBuilder() {
        if (body2WrenchBuilder_ == null) {
          body2WrenchBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzWrench.Wrench, gazebo.msgs.GzWrench.Wrench.Builder, gazebo.msgs.GzWrench.WrenchOrBuilder>(
                  body2Wrench_,
                  getParentForChildren(),
                  isClean());
          body2Wrench_ = null;
        }
        return body2WrenchBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.JointWrench)
    }

    static {
      defaultInstance = new JointWrench(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.JointWrench)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_JointWrench_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_JointWrench_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\022joint_wrench.proto\022\013gazebo.msgs\032\014wrenc" +
      "h.proto\"\265\001\n\013JointWrench\022\023\n\013body_1_name\030\001" +
      " \002(\t\022\021\n\tbody_1_id\030\002 \002(\r\022\023\n\013body_2_name\030\003" +
      " \002(\t\022\021\n\tbody_2_id\030\004 \002(\r\022*\n\rbody_1_wrench" +
      "\030\005 \002(\0132\023.gazebo.msgs.Wrench\022*\n\rbody_2_wr" +
      "ench\030\006 \002(\0132\023.gazebo.msgs.WrenchB\017B\rGzJoi" +
      "ntWrench"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gazebo_msgs_JointWrench_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gazebo_msgs_JointWrench_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_JointWrench_descriptor,
              new java.lang.String[] { "Body1Name", "Body1Id", "Body2Name", "Body2Id", "Body1Wrench", "Body2Wrench", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GzWrench.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
