// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: log_status.proto

package gazebo.msgs;

public final class GzLogStatus {
  private GzLogStatus() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface LogStatusOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // optional .gazebo.msgs.Time sim_time = 1;
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    boolean hasSimTime();
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    gazebo.msgs.GzTime.Time getSimTime();
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    gazebo.msgs.GzTime.TimeOrBuilder getSimTimeOrBuilder();

    // optional .gazebo.msgs.LogStatus.LogFile log_file = 2;
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    boolean hasLogFile();
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    gazebo.msgs.GzLogStatus.LogStatus.LogFile getLogFile();
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder getLogFileOrBuilder();
  }
  /**
   * Protobuf type {@code gazebo.msgs.LogStatus}
   */
  public static final class LogStatus extends
      com.google.protobuf.GeneratedMessage
      implements LogStatusOrBuilder {
    // Use LogStatus.newBuilder() to construct.
    private LogStatus(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private LogStatus(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final LogStatus defaultInstance;
    public static LogStatus getDefaultInstance() {
      return defaultInstance;
    }

    public LogStatus getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private LogStatus(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              gazebo.msgs.GzTime.Time.Builder subBuilder = null;
              if (((bitField0_ & 0x00000001) == 0x00000001)) {
                subBuilder = simTime_.toBuilder();
              }
              simTime_ = input.readMessage(gazebo.msgs.GzTime.Time.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(simTime_);
                simTime_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000001;
              break;
            }
            case 18: {
              gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder subBuilder = null;
              if (((bitField0_ & 0x00000002) == 0x00000002)) {
                subBuilder = logFile_.toBuilder();
              }
              logFile_ = input.readMessage(gazebo.msgs.GzLogStatus.LogStatus.LogFile.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(logFile_);
                logFile_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000002;
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.GzLogStatus.LogStatus.class, gazebo.msgs.GzLogStatus.LogStatus.Builder.class);
    }

    public static com.google.protobuf.Parser<LogStatus> PARSER =
        new com.google.protobuf.AbstractParser<LogStatus>() {
      public LogStatus parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new LogStatus(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<LogStatus> getParserForType() {
      return PARSER;
    }

    public interface LogFileOrBuilder
        extends com.google.protobuf.MessageOrBuilder {

      // optional string uri = 1;
      /**
       * <code>optional string uri = 1;</code>
       */
      boolean hasUri();
      /**
       * <code>optional string uri = 1;</code>
       */
      java.lang.String getUri();
      /**
       * <code>optional string uri = 1;</code>
       */
      com.google.protobuf.ByteString
          getUriBytes();

      // optional string base_path = 2;
      /**
       * <code>optional string base_path = 2;</code>
       */
      boolean hasBasePath();
      /**
       * <code>optional string base_path = 2;</code>
       */
      java.lang.String getBasePath();
      /**
       * <code>optional string base_path = 2;</code>
       */
      com.google.protobuf.ByteString
          getBasePathBytes();

      // optional string full_path = 3;
      /**
       * <code>optional string full_path = 3;</code>
       */
      boolean hasFullPath();
      /**
       * <code>optional string full_path = 3;</code>
       */
      java.lang.String getFullPath();
      /**
       * <code>optional string full_path = 3;</code>
       */
      com.google.protobuf.ByteString
          getFullPathBytes();

      // optional float size = 4;
      /**
       * <code>optional float size = 4;</code>
       */
      boolean hasSize();
      /**
       * <code>optional float size = 4;</code>
       */
      float getSize();

      // optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
       */
      boolean hasSizeUnits();
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
       */
      gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units getSizeUnits();
    }
    /**
     * Protobuf type {@code gazebo.msgs.LogStatus.LogFile}
     */
    public static final class LogFile extends
        com.google.protobuf.GeneratedMessage
        implements LogFileOrBuilder {
      // Use LogFile.newBuilder() to construct.
      private LogFile(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
        super(builder);
        this.unknownFields = builder.getUnknownFields();
      }
      private LogFile(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

      private static final LogFile defaultInstance;
      public static LogFile getDefaultInstance() {
        return defaultInstance;
      }

      public LogFile getDefaultInstanceForType() {
        return defaultInstance;
      }

      private final com.google.protobuf.UnknownFieldSet unknownFields;
      @java.lang.Override
      public final com.google.protobuf.UnknownFieldSet
          getUnknownFields() {
        return this.unknownFields;
      }
      private LogFile(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        initFields();
        int mutable_bitField0_ = 0;
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
            com.google.protobuf.UnknownFieldSet.newBuilder();
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!parseUnknownField(input, unknownFields,
                                       extensionRegistry, tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                bitField0_ |= 0x00000001;
                uri_ = input.readBytes();
                break;
              }
              case 18: {
                bitField0_ |= 0x00000002;
                basePath_ = input.readBytes();
                break;
              }
              case 26: {
                bitField0_ |= 0x00000004;
                fullPath_ = input.readBytes();
                break;
              }
              case 37: {
                bitField0_ |= 0x00000008;
                size_ = input.readFloat();
                break;
              }
              case 40: {
                int rawValue = input.readEnum();
                gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units value = gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units.valueOf(rawValue);
                if (value == null) {
                  unknownFields.mergeVarintField(5, rawValue);
                } else {
                  bitField0_ |= 0x00000010;
                  sizeUnits_ = value;
                }
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(this);
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(
              e.getMessage()).setUnfinishedMessage(this);
        } finally {
          this.unknownFields = unknownFields.build();
          makeExtensionsImmutable();
        }
      }
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_LogFile_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_LogFile_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzLogStatus.LogStatus.LogFile.class, gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder.class);
      }

      public static com.google.protobuf.Parser<LogFile> PARSER =
          new com.google.protobuf.AbstractParser<LogFile>() {
        public LogFile parsePartialFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws com.google.protobuf.InvalidProtocolBufferException {
          return new LogFile(input, extensionRegistry);
        }
      };

      @java.lang.Override
      public com.google.protobuf.Parser<LogFile> getParserForType() {
        return PARSER;
      }

      /**
       * Protobuf enum {@code gazebo.msgs.LogStatus.LogFile.Units}
       */
      public enum Units
          implements com.google.protobuf.ProtocolMessageEnum {
        /**
         * <code>BYTES = 1;</code>
         */
        BYTES(0, 1),
        /**
         * <code>K_BYTES = 2;</code>
         */
        K_BYTES(1, 2),
        /**
         * <code>M_BYTES = 3;</code>
         */
        M_BYTES(2, 3),
        /**
         * <code>G_BYTES = 4;</code>
         */
        G_BYTES(3, 4),
        ;

        /**
         * <code>BYTES = 1;</code>
         */
        public static final int BYTES_VALUE = 1;
        /**
         * <code>K_BYTES = 2;</code>
         */
        public static final int K_BYTES_VALUE = 2;
        /**
         * <code>M_BYTES = 3;</code>
         */
        public static final int M_BYTES_VALUE = 3;
        /**
         * <code>G_BYTES = 4;</code>
         */
        public static final int G_BYTES_VALUE = 4;


        public final int getNumber() { return value; }

        public static Units valueOf(int value) {
          switch (value) {
            case 1: return BYTES;
            case 2: return K_BYTES;
            case 3: return M_BYTES;
            case 4: return G_BYTES;
            default: return null;
          }
        }

        public static com.google.protobuf.Internal.EnumLiteMap<Units>
            internalGetValueMap() {
          return internalValueMap;
        }
        private static com.google.protobuf.Internal.EnumLiteMap<Units>
            internalValueMap =
              new com.google.protobuf.Internal.EnumLiteMap<Units>() {
                public Units findValueByNumber(int number) {
                  return Units.valueOf(number);
                }
              };

        public final com.google.protobuf.Descriptors.EnumValueDescriptor
            getValueDescriptor() {
          return getDescriptor().getValues().get(index);
        }
        public final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptorForType() {
          return getDescriptor();
        }
        public static final com.google.protobuf.Descriptors.EnumDescriptor
            getDescriptor() {
          return gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDescriptor().getEnumTypes().get(0);
        }

        private static final Units[] VALUES = values();

        public static Units valueOf(
            com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
          if (desc.getType() != getDescriptor()) {
            throw new java.lang.IllegalArgumentException(
              "EnumValueDescriptor is not for this type.");
          }
          return VALUES[desc.getIndex()];
        }

        private final int index;
        private final int value;

        private Units(int index, int value) {
          this.index = index;
          this.value = value;
        }

        // @@protoc_insertion_point(enum_scope:gazebo.msgs.LogStatus.LogFile.Units)
      }

      private int bitField0_;
      // optional string uri = 1;
      public static final int URI_FIELD_NUMBER = 1;
      private java.lang.Object uri_;
      /**
       * <code>optional string uri = 1;</code>
       */
      public boolean hasUri() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional string uri = 1;</code>
       */
      public java.lang.String getUri() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            uri_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string uri = 1;</code>
       */
      public com.google.protobuf.ByteString
          getUriBytes() {
        java.lang.Object ref = uri_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          uri_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string base_path = 2;
      public static final int BASE_PATH_FIELD_NUMBER = 2;
      private java.lang.Object basePath_;
      /**
       * <code>optional string base_path = 2;</code>
       */
      public boolean hasBasePath() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional string base_path = 2;</code>
       */
      public java.lang.String getBasePath() {
        java.lang.Object ref = basePath_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            basePath_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string base_path = 2;</code>
       */
      public com.google.protobuf.ByteString
          getBasePathBytes() {
        java.lang.Object ref = basePath_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          basePath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional string full_path = 3;
      public static final int FULL_PATH_FIELD_NUMBER = 3;
      private java.lang.Object fullPath_;
      /**
       * <code>optional string full_path = 3;</code>
       */
      public boolean hasFullPath() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional string full_path = 3;</code>
       */
      public java.lang.String getFullPath() {
        java.lang.Object ref = fullPath_;
        if (ref instanceof java.lang.String) {
          return (java.lang.String) ref;
        } else {
          com.google.protobuf.ByteString bs = 
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          if (bs.isValidUtf8()) {
            fullPath_ = s;
          }
          return s;
        }
      }
      /**
       * <code>optional string full_path = 3;</code>
       */
      public com.google.protobuf.ByteString
          getFullPathBytes() {
        java.lang.Object ref = fullPath_;
        if (ref instanceof java.lang.String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          fullPath_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }

      // optional float size = 4;
      public static final int SIZE_FIELD_NUMBER = 4;
      private float size_;
      /**
       * <code>optional float size = 4;</code>
       */
      public boolean hasSize() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional float size = 4;</code>
       */
      public float getSize() {
        return size_;
      }

      // optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;
      public static final int SIZE_UNITS_FIELD_NUMBER = 5;
      private gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units sizeUnits_;
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
       */
      public boolean hasSizeUnits() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
       */
      public gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units getSizeUnits() {
        return sizeUnits_;
      }

      private void initFields() {
        uri_ = "";
        basePath_ = "";
        fullPath_ = "";
        size_ = 0F;
        sizeUnits_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units.BYTES;
      }
      private byte memoizedIsInitialized = -1;
      public final boolean isInitialized() {
        byte isInitialized = memoizedIsInitialized;
        if (isInitialized != -1) return isInitialized == 1;

        memoizedIsInitialized = 1;
        return true;
      }

      public void writeTo(com.google.protobuf.CodedOutputStream output)
                          throws java.io.IOException {
        getSerializedSize();
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          output.writeBytes(1, getUriBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          output.writeBytes(2, getBasePathBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          output.writeBytes(3, getFullPathBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          output.writeFloat(4, size_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          output.writeEnum(5, sizeUnits_.getNumber());
        }
        getUnknownFields().writeTo(output);
      }

      private int memoizedSerializedSize = -1;
      public int getSerializedSize() {
        int size = memoizedSerializedSize;
        if (size != -1) return size;

        size = 0;
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(1, getUriBytes());
        }
        if (((bitField0_ & 0x00000002) == 0x00000002)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(2, getBasePathBytes());
        }
        if (((bitField0_ & 0x00000004) == 0x00000004)) {
          size += com.google.protobuf.CodedOutputStream
            .computeBytesSize(3, getFullPathBytes());
        }
        if (((bitField0_ & 0x00000008) == 0x00000008)) {
          size += com.google.protobuf.CodedOutputStream
            .computeFloatSize(4, size_);
        }
        if (((bitField0_ & 0x00000010) == 0x00000010)) {
          size += com.google.protobuf.CodedOutputStream
            .computeEnumSize(5, sizeUnits_.getNumber());
        }
        size += getUnknownFields().getSerializedSize();
        memoizedSerializedSize = size;
        return size;
      }

      private static final long serialVersionUID = 0L;
      @java.lang.Override
      protected java.lang.Object writeReplace()
          throws java.io.ObjectStreamException {
        return super.writeReplace();
      }

      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          com.google.protobuf.ByteString data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          com.google.protobuf.ByteString data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(byte[] data)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          byte[] data,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return PARSER.parseFrom(data, extensionRegistry);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseDelimitedFrom(java.io.InputStream input)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseDelimitedFrom(
          java.io.InputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseDelimitedFrom(input, extensionRegistry);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          com.google.protobuf.CodedInputStream input)
          throws java.io.IOException {
        return PARSER.parseFrom(input);
      }
      public static gazebo.msgs.GzLogStatus.LogStatus.LogFile parseFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        return PARSER.parseFrom(input, extensionRegistry);
      }

      public static Builder newBuilder() { return Builder.create(); }
      public Builder newBuilderForType() { return newBuilder(); }
      public static Builder newBuilder(gazebo.msgs.GzLogStatus.LogStatus.LogFile prototype) {
        return newBuilder().mergeFrom(prototype);
      }
      public Builder toBuilder() { return newBuilder(this); }

      @java.lang.Override
      protected Builder newBuilderForType(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        Builder builder = new Builder(parent);
        return builder;
      }
      /**
       * Protobuf type {@code gazebo.msgs.LogStatus.LogFile}
       */
      public static final class Builder extends
          com.google.protobuf.GeneratedMessage.Builder<Builder>
         implements gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder {
        public static final com.google.protobuf.Descriptors.Descriptor
            getDescriptor() {
          return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_LogFile_descriptor;
        }

        protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
            internalGetFieldAccessorTable() {
          return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_LogFile_fieldAccessorTable
              .ensureFieldAccessorsInitialized(
                  gazebo.msgs.GzLogStatus.LogStatus.LogFile.class, gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder.class);
        }

        // Construct using gazebo.msgs.GzLogStatus.LogStatus.LogFile.newBuilder()
        private Builder() {
          maybeForceBuilderInitialization();
        }

        private Builder(
            com.google.protobuf.GeneratedMessage.BuilderParent parent) {
          super(parent);
          maybeForceBuilderInitialization();
        }
        private void maybeForceBuilderInitialization() {
          if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          }
        }
        private static Builder create() {
          return new Builder();
        }

        public Builder clear() {
          super.clear();
          uri_ = "";
          bitField0_ = (bitField0_ & ~0x00000001);
          basePath_ = "";
          bitField0_ = (bitField0_ & ~0x00000002);
          fullPath_ = "";
          bitField0_ = (bitField0_ & ~0x00000004);
          size_ = 0F;
          bitField0_ = (bitField0_ & ~0x00000008);
          sizeUnits_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units.BYTES;
          bitField0_ = (bitField0_ & ~0x00000010);
          return this;
        }

        public Builder clone() {
          return create().mergeFrom(buildPartial());
        }

        public com.google.protobuf.Descriptors.Descriptor
            getDescriptorForType() {
          return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_LogFile_descriptor;
        }

        public gazebo.msgs.GzLogStatus.LogStatus.LogFile getDefaultInstanceForType() {
          return gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance();
        }

        public gazebo.msgs.GzLogStatus.LogStatus.LogFile build() {
          gazebo.msgs.GzLogStatus.LogStatus.LogFile result = buildPartial();
          if (!result.isInitialized()) {
            throw newUninitializedMessageException(result);
          }
          return result;
        }

        public gazebo.msgs.GzLogStatus.LogStatus.LogFile buildPartial() {
          gazebo.msgs.GzLogStatus.LogStatus.LogFile result = new gazebo.msgs.GzLogStatus.LogStatus.LogFile(this);
          int from_bitField0_ = bitField0_;
          int to_bitField0_ = 0;
          if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
            to_bitField0_ |= 0x00000001;
          }
          result.uri_ = uri_;
          if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
            to_bitField0_ |= 0x00000002;
          }
          result.basePath_ = basePath_;
          if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
            to_bitField0_ |= 0x00000004;
          }
          result.fullPath_ = fullPath_;
          if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
            to_bitField0_ |= 0x00000008;
          }
          result.size_ = size_;
          if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
            to_bitField0_ |= 0x00000010;
          }
          result.sizeUnits_ = sizeUnits_;
          result.bitField0_ = to_bitField0_;
          onBuilt();
          return result;
        }

        public Builder mergeFrom(com.google.protobuf.Message other) {
          if (other instanceof gazebo.msgs.GzLogStatus.LogStatus.LogFile) {
            return mergeFrom((gazebo.msgs.GzLogStatus.LogStatus.LogFile)other);
          } else {
            super.mergeFrom(other);
            return this;
          }
        }

        public Builder mergeFrom(gazebo.msgs.GzLogStatus.LogStatus.LogFile other) {
          if (other == gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance()) return this;
          if (other.hasUri()) {
            bitField0_ |= 0x00000001;
            uri_ = other.uri_;
            onChanged();
          }
          if (other.hasBasePath()) {
            bitField0_ |= 0x00000002;
            basePath_ = other.basePath_;
            onChanged();
          }
          if (other.hasFullPath()) {
            bitField0_ |= 0x00000004;
            fullPath_ = other.fullPath_;
            onChanged();
          }
          if (other.hasSize()) {
            setSize(other.getSize());
          }
          if (other.hasSizeUnits()) {
            setSizeUnits(other.getSizeUnits());
          }
          this.mergeUnknownFields(other.getUnknownFields());
          return this;
        }

        public final boolean isInitialized() {
          return true;
        }

        public Builder mergeFrom(
            com.google.protobuf.CodedInputStream input,
            com.google.protobuf.ExtensionRegistryLite extensionRegistry)
            throws java.io.IOException {
          gazebo.msgs.GzLogStatus.LogStatus.LogFile parsedMessage = null;
          try {
            parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
          } catch (com.google.protobuf.InvalidProtocolBufferException e) {
            parsedMessage = (gazebo.msgs.GzLogStatus.LogStatus.LogFile) e.getUnfinishedMessage();
            throw e;
          } finally {
            if (parsedMessage != null) {
              mergeFrom(parsedMessage);
            }
          }
          return this;
        }
        private int bitField0_;

        // optional string uri = 1;
        private java.lang.Object uri_ = "";
        /**
         * <code>optional string uri = 1;</code>
         */
        public boolean hasUri() {
          return ((bitField0_ & 0x00000001) == 0x00000001);
        }
        /**
         * <code>optional string uri = 1;</code>
         */
        public java.lang.String getUri() {
          java.lang.Object ref = uri_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            uri_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string uri = 1;</code>
         */
        public com.google.protobuf.ByteString
            getUriBytes() {
          java.lang.Object ref = uri_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            uri_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string uri = 1;</code>
         */
        public Builder setUri(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          uri_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri = 1;</code>
         */
        public Builder clearUri() {
          bitField0_ = (bitField0_ & ~0x00000001);
          uri_ = getDefaultInstance().getUri();
          onChanged();
          return this;
        }
        /**
         * <code>optional string uri = 1;</code>
         */
        public Builder setUriBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
          uri_ = value;
          onChanged();
          return this;
        }

        // optional string base_path = 2;
        private java.lang.Object basePath_ = "";
        /**
         * <code>optional string base_path = 2;</code>
         */
        public boolean hasBasePath() {
          return ((bitField0_ & 0x00000002) == 0x00000002);
        }
        /**
         * <code>optional string base_path = 2;</code>
         */
        public java.lang.String getBasePath() {
          java.lang.Object ref = basePath_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            basePath_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string base_path = 2;</code>
         */
        public com.google.protobuf.ByteString
            getBasePathBytes() {
          java.lang.Object ref = basePath_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            basePath_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string base_path = 2;</code>
         */
        public Builder setBasePath(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          basePath_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string base_path = 2;</code>
         */
        public Builder clearBasePath() {
          bitField0_ = (bitField0_ & ~0x00000002);
          basePath_ = getDefaultInstance().getBasePath();
          onChanged();
          return this;
        }
        /**
         * <code>optional string base_path = 2;</code>
         */
        public Builder setBasePathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
          basePath_ = value;
          onChanged();
          return this;
        }

        // optional string full_path = 3;
        private java.lang.Object fullPath_ = "";
        /**
         * <code>optional string full_path = 3;</code>
         */
        public boolean hasFullPath() {
          return ((bitField0_ & 0x00000004) == 0x00000004);
        }
        /**
         * <code>optional string full_path = 3;</code>
         */
        public java.lang.String getFullPath() {
          java.lang.Object ref = fullPath_;
          if (!(ref instanceof java.lang.String)) {
            java.lang.String s = ((com.google.protobuf.ByteString) ref)
                .toStringUtf8();
            fullPath_ = s;
            return s;
          } else {
            return (java.lang.String) ref;
          }
        }
        /**
         * <code>optional string full_path = 3;</code>
         */
        public com.google.protobuf.ByteString
            getFullPathBytes() {
          java.lang.Object ref = fullPath_;
          if (ref instanceof String) {
            com.google.protobuf.ByteString b = 
                com.google.protobuf.ByteString.copyFromUtf8(
                    (java.lang.String) ref);
            fullPath_ = b;
            return b;
          } else {
            return (com.google.protobuf.ByteString) ref;
          }
        }
        /**
         * <code>optional string full_path = 3;</code>
         */
        public Builder setFullPath(
            java.lang.String value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          fullPath_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional string full_path = 3;</code>
         */
        public Builder clearFullPath() {
          bitField0_ = (bitField0_ & ~0x00000004);
          fullPath_ = getDefaultInstance().getFullPath();
          onChanged();
          return this;
        }
        /**
         * <code>optional string full_path = 3;</code>
         */
        public Builder setFullPathBytes(
            com.google.protobuf.ByteString value) {
          if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000004;
          fullPath_ = value;
          onChanged();
          return this;
        }

        // optional float size = 4;
        private float size_ ;
        /**
         * <code>optional float size = 4;</code>
         */
        public boolean hasSize() {
          return ((bitField0_ & 0x00000008) == 0x00000008);
        }
        /**
         * <code>optional float size = 4;</code>
         */
        public float getSize() {
          return size_;
        }
        /**
         * <code>optional float size = 4;</code>
         */
        public Builder setSize(float value) {
          bitField0_ |= 0x00000008;
          size_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional float size = 4;</code>
         */
        public Builder clearSize() {
          bitField0_ = (bitField0_ & ~0x00000008);
          size_ = 0F;
          onChanged();
          return this;
        }

        // optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;
        private gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units sizeUnits_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units.BYTES;
        /**
         * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
         */
        public boolean hasSizeUnits() {
          return ((bitField0_ & 0x00000010) == 0x00000010);
        }
        /**
         * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
         */
        public gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units getSizeUnits() {
          return sizeUnits_;
        }
        /**
         * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
         */
        public Builder setSizeUnits(gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units value) {
          if (value == null) {
            throw new NullPointerException();
          }
          bitField0_ |= 0x00000010;
          sizeUnits_ = value;
          onChanged();
          return this;
        }
        /**
         * <code>optional .gazebo.msgs.LogStatus.LogFile.Units size_units = 5;</code>
         */
        public Builder clearSizeUnits() {
          bitField0_ = (bitField0_ & ~0x00000010);
          sizeUnits_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.Units.BYTES;
          onChanged();
          return this;
        }

        // @@protoc_insertion_point(builder_scope:gazebo.msgs.LogStatus.LogFile)
      }

      static {
        defaultInstance = new LogFile(true);
        defaultInstance.initFields();
      }

      // @@protoc_insertion_point(class_scope:gazebo.msgs.LogStatus.LogFile)
    }

    private int bitField0_;
    // optional .gazebo.msgs.Time sim_time = 1;
    public static final int SIM_TIME_FIELD_NUMBER = 1;
    private gazebo.msgs.GzTime.Time simTime_;
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    public boolean hasSimTime() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    public gazebo.msgs.GzTime.Time getSimTime() {
      return simTime_;
    }
    /**
     * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
     */
    public gazebo.msgs.GzTime.TimeOrBuilder getSimTimeOrBuilder() {
      return simTime_;
    }

    // optional .gazebo.msgs.LogStatus.LogFile log_file = 2;
    public static final int LOG_FILE_FIELD_NUMBER = 2;
    private gazebo.msgs.GzLogStatus.LogStatus.LogFile logFile_;
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    public boolean hasLogFile() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    public gazebo.msgs.GzLogStatus.LogStatus.LogFile getLogFile() {
      return logFile_;
    }
    /**
     * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
     */
    public gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder getLogFileOrBuilder() {
      return logFile_;
    }

    private void initFields() {
      simTime_ = gazebo.msgs.GzTime.Time.getDefaultInstance();
      logFile_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (hasSimTime()) {
        if (!getSimTime().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeMessage(1, simTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, logFile_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, simTime_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, logFile_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzLogStatus.LogStatus parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gazebo.msgs.GzLogStatus.LogStatus prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.LogStatus}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gazebo.msgs.GzLogStatus.LogStatusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzLogStatus.LogStatus.class, gazebo.msgs.GzLogStatus.LogStatus.Builder.class);
      }

      // Construct using gazebo.msgs.GzLogStatus.LogStatus.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getSimTimeFieldBuilder();
          getLogFileFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        if (simTimeBuilder_ == null) {
          simTime_ = gazebo.msgs.GzTime.Time.getDefaultInstance();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        if (logFileBuilder_ == null) {
          logFile_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance();
        } else {
          logFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.GzLogStatus.internal_static_gazebo_msgs_LogStatus_descriptor;
      }

      public gazebo.msgs.GzLogStatus.LogStatus getDefaultInstanceForType() {
        return gazebo.msgs.GzLogStatus.LogStatus.getDefaultInstance();
      }

      public gazebo.msgs.GzLogStatus.LogStatus build() {
        gazebo.msgs.GzLogStatus.LogStatus result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gazebo.msgs.GzLogStatus.LogStatus buildPartial() {
        gazebo.msgs.GzLogStatus.LogStatus result = new gazebo.msgs.GzLogStatus.LogStatus(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        if (simTimeBuilder_ == null) {
          result.simTime_ = simTime_;
        } else {
          result.simTime_ = simTimeBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (logFileBuilder_ == null) {
          result.logFile_ = logFile_;
        } else {
          result.logFile_ = logFileBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.GzLogStatus.LogStatus) {
          return mergeFrom((gazebo.msgs.GzLogStatus.LogStatus)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.GzLogStatus.LogStatus other) {
        if (other == gazebo.msgs.GzLogStatus.LogStatus.getDefaultInstance()) return this;
        if (other.hasSimTime()) {
          mergeSimTime(other.getSimTime());
        }
        if (other.hasLogFile()) {
          mergeLogFile(other.getLogFile());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (hasSimTime()) {
          if (!getSimTime().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.GzLogStatus.LogStatus parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.GzLogStatus.LogStatus) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // optional .gazebo.msgs.Time sim_time = 1;
      private gazebo.msgs.GzTime.Time simTime_ = gazebo.msgs.GzTime.Time.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder> simTimeBuilder_;
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public boolean hasSimTime() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public gazebo.msgs.GzTime.Time getSimTime() {
        if (simTimeBuilder_ == null) {
          return simTime_;
        } else {
          return simTimeBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public Builder setSimTime(gazebo.msgs.GzTime.Time value) {
        if (simTimeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          simTime_ = value;
          onChanged();
        } else {
          simTimeBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public Builder setSimTime(
          gazebo.msgs.GzTime.Time.Builder builderForValue) {
        if (simTimeBuilder_ == null) {
          simTime_ = builderForValue.build();
          onChanged();
        } else {
          simTimeBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public Builder mergeSimTime(gazebo.msgs.GzTime.Time value) {
        if (simTimeBuilder_ == null) {
          if (((bitField0_ & 0x00000001) == 0x00000001) &&
              simTime_ != gazebo.msgs.GzTime.Time.getDefaultInstance()) {
            simTime_ =
              gazebo.msgs.GzTime.Time.newBuilder(simTime_).mergeFrom(value).buildPartial();
          } else {
            simTime_ = value;
          }
          onChanged();
        } else {
          simTimeBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000001;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public Builder clearSimTime() {
        if (simTimeBuilder_ == null) {
          simTime_ = gazebo.msgs.GzTime.Time.getDefaultInstance();
          onChanged();
        } else {
          simTimeBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000001);
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public gazebo.msgs.GzTime.Time.Builder getSimTimeBuilder() {
        bitField0_ |= 0x00000001;
        onChanged();
        return getSimTimeFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      public gazebo.msgs.GzTime.TimeOrBuilder getSimTimeOrBuilder() {
        if (simTimeBuilder_ != null) {
          return simTimeBuilder_.getMessageOrBuilder();
        } else {
          return simTime_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.Time sim_time = 1;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder> 
          getSimTimeFieldBuilder() {
        if (simTimeBuilder_ == null) {
          simTimeBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder>(
                  simTime_,
                  getParentForChildren(),
                  isClean());
          simTime_ = null;
        }
        return simTimeBuilder_;
      }

      // optional .gazebo.msgs.LogStatus.LogFile log_file = 2;
      private gazebo.msgs.GzLogStatus.LogStatus.LogFile logFile_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzLogStatus.LogStatus.LogFile, gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder, gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder> logFileBuilder_;
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public boolean hasLogFile() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public gazebo.msgs.GzLogStatus.LogStatus.LogFile getLogFile() {
        if (logFileBuilder_ == null) {
          return logFile_;
        } else {
          return logFileBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public Builder setLogFile(gazebo.msgs.GzLogStatus.LogStatus.LogFile value) {
        if (logFileBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          logFile_ = value;
          onChanged();
        } else {
          logFileBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public Builder setLogFile(
          gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder builderForValue) {
        if (logFileBuilder_ == null) {
          logFile_ = builderForValue.build();
          onChanged();
        } else {
          logFileBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public Builder mergeLogFile(gazebo.msgs.GzLogStatus.LogStatus.LogFile value) {
        if (logFileBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              logFile_ != gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance()) {
            logFile_ =
              gazebo.msgs.GzLogStatus.LogStatus.LogFile.newBuilder(logFile_).mergeFrom(value).buildPartial();
          } else {
            logFile_ = value;
          }
          onChanged();
        } else {
          logFileBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public Builder clearLogFile() {
        if (logFileBuilder_ == null) {
          logFile_ = gazebo.msgs.GzLogStatus.LogStatus.LogFile.getDefaultInstance();
          onChanged();
        } else {
          logFileBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder getLogFileBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getLogFileFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      public gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder getLogFileOrBuilder() {
        if (logFileBuilder_ != null) {
          return logFileBuilder_.getMessageOrBuilder();
        } else {
          return logFile_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.LogStatus.LogFile log_file = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzLogStatus.LogStatus.LogFile, gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder, gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder> 
          getLogFileFieldBuilder() {
        if (logFileBuilder_ == null) {
          logFileBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzLogStatus.LogStatus.LogFile, gazebo.msgs.GzLogStatus.LogStatus.LogFile.Builder, gazebo.msgs.GzLogStatus.LogStatus.LogFileOrBuilder>(
                  logFile_,
                  getParentForChildren(),
                  isClean());
          logFile_ = null;
        }
        return logFileBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.LogStatus)
    }

    static {
      defaultInstance = new LogStatus(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.LogStatus)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_LogStatus_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_LogStatus_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_LogStatus_LogFile_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_LogStatus_LogFile_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020log_status.proto\022\013gazebo.msgs\032\ntime.pr" +
      "oto\"\244\002\n\tLogStatus\022#\n\010sim_time\030\001 \001(\0132\021.ga" +
      "zebo.msgs.Time\0220\n\010log_file\030\002 \001(\0132\036.gazeb" +
      "o.msgs.LogStatus.LogFile\032\277\001\n\007LogFile\022\013\n\003" +
      "uri\030\001 \001(\t\022\021\n\tbase_path\030\002 \001(\t\022\021\n\tfull_pat" +
      "h\030\003 \001(\t\022\014\n\004size\030\004 \001(\002\0228\n\nsize_units\030\005 \001(" +
      "\0162$.gazebo.msgs.LogStatus.LogFile.Units\"" +
      "9\n\005Units\022\t\n\005BYTES\020\001\022\013\n\007K_BYTES\020\002\022\013\n\007M_BY" +
      "TES\020\003\022\013\n\007G_BYTES\020\004B\rB\013GzLogStatus"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gazebo_msgs_LogStatus_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gazebo_msgs_LogStatus_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_LogStatus_descriptor,
              new java.lang.String[] { "SimTime", "LogFile", });
          internal_static_gazebo_msgs_LogStatus_LogFile_descriptor =
            internal_static_gazebo_msgs_LogStatus_descriptor.getNestedTypes().get(0);
          internal_static_gazebo_msgs_LogStatus_LogFile_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_LogStatus_LogFile_descriptor,
              new java.lang.String[] { "Uri", "BasePath", "FullPath", "Size", "SizeUnits", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GzTime.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
