// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: model.proto

package gazebo.msgs;

public final class GzModel {
  private GzModel() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface ModelOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string name = 1;
    /**
     * <code>required string name = 1;</code>
     */
    boolean hasName();
    /**
     * <code>required string name = 1;</code>
     */
    java.lang.String getName();
    /**
     * <code>required string name = 1;</code>
     */
    com.google.protobuf.ByteString
        getNameBytes();

    // optional uint32 id = 2;
    /**
     * <code>optional uint32 id = 2;</code>
     */
    boolean hasId();
    /**
     * <code>optional uint32 id = 2;</code>
     */
    int getId();

    // optional bool is_static = 3;
    /**
     * <code>optional bool is_static = 3;</code>
     */
    boolean hasIsStatic();
    /**
     * <code>optional bool is_static = 3;</code>
     */
    boolean getIsStatic();

    // optional .gazebo.msgs.Pose pose = 4;
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    boolean hasPose();
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    gazebo.msgs.GzPose.Pose getPose();
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder();

    // repeated .gazebo.msgs.Joint joint = 5;
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    java.util.List<gazebo.msgs.GzJoint.Joint> 
        getJointList();
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    gazebo.msgs.GzJoint.Joint getJoint(int index);
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    int getJointCount();
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    java.util.List<? extends gazebo.msgs.GzJoint.JointOrBuilder> 
        getJointOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    gazebo.msgs.GzJoint.JointOrBuilder getJointOrBuilder(
        int index);

    // repeated .gazebo.msgs.Link link = 6;
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    java.util.List<gazebo.msgs.GzLink.Link> 
        getLinkList();
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    gazebo.msgs.GzLink.Link getLink(int index);
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    int getLinkCount();
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    java.util.List<? extends gazebo.msgs.GzLink.LinkOrBuilder> 
        getLinkOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    gazebo.msgs.GzLink.LinkOrBuilder getLinkOrBuilder(
        int index);

    // optional bool deleted = 7;
    /**
     * <code>optional bool deleted = 7;</code>
     */
    boolean hasDeleted();
    /**
     * <code>optional bool deleted = 7;</code>
     */
    boolean getDeleted();

    // repeated .gazebo.msgs.Visual visual = 8;
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    java.util.List<gazebo.msgs.GzVisual.Visual> 
        getVisualList();
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    gazebo.msgs.GzVisual.Visual getVisual(int index);
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    int getVisualCount();
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    java.util.List<? extends gazebo.msgs.GzVisual.VisualOrBuilder> 
        getVisualOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    gazebo.msgs.GzVisual.VisualOrBuilder getVisualOrBuilder(
        int index);

    // optional .gazebo.msgs.Vector3d scale = 9;
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    boolean hasScale();
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    gazebo.msgs.GzVector3d.Vector3d getScale();
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    gazebo.msgs.GzVector3d.Vector3dOrBuilder getScaleOrBuilder();

    // optional bool self_collide = 10;
    /**
     * <code>optional bool self_collide = 10;</code>
     */
    boolean hasSelfCollide();
    /**
     * <code>optional bool self_collide = 10;</code>
     */
    boolean getSelfCollide();
  }
  /**
   * Protobuf type {@code gazebo.msgs.Model}
   */
  public static final class Model extends
      com.google.protobuf.GeneratedMessage
      implements ModelOrBuilder {
    // Use Model.newBuilder() to construct.
    private Model(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Model(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Model defaultInstance;
    public static Model getDefaultInstance() {
      return defaultInstance;
    }

    public Model getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Model(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              name_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              id_ = input.readUInt32();
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              isStatic_ = input.readBool();
              break;
            }
            case 34: {
              gazebo.msgs.GzPose.Pose.Builder subBuilder = null;
              if (((bitField0_ & 0x00000008) == 0x00000008)) {
                subBuilder = pose_.toBuilder();
              }
              pose_ = input.readMessage(gazebo.msgs.GzPose.Pose.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(pose_);
                pose_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000008;
              break;
            }
            case 42: {
              if (!((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
                joint_ = new java.util.ArrayList<gazebo.msgs.GzJoint.Joint>();
                mutable_bitField0_ |= 0x00000010;
              }
              joint_.add(input.readMessage(gazebo.msgs.GzJoint.Joint.PARSER, extensionRegistry));
              break;
            }
            case 50: {
              if (!((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
                link_ = new java.util.ArrayList<gazebo.msgs.GzLink.Link>();
                mutable_bitField0_ |= 0x00000020;
              }
              link_.add(input.readMessage(gazebo.msgs.GzLink.Link.PARSER, extensionRegistry));
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              deleted_ = input.readBool();
              break;
            }
            case 66: {
              if (!((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
                visual_ = new java.util.ArrayList<gazebo.msgs.GzVisual.Visual>();
                mutable_bitField0_ |= 0x00000080;
              }
              visual_.add(input.readMessage(gazebo.msgs.GzVisual.Visual.PARSER, extensionRegistry));
              break;
            }
            case 74: {
              gazebo.msgs.GzVector3d.Vector3d.Builder subBuilder = null;
              if (((bitField0_ & 0x00000020) == 0x00000020)) {
                subBuilder = scale_.toBuilder();
              }
              scale_ = input.readMessage(gazebo.msgs.GzVector3d.Vector3d.PARSER, extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(scale_);
                scale_ = subBuilder.buildPartial();
              }
              bitField0_ |= 0x00000020;
              break;
            }
            case 80: {
              bitField0_ |= 0x00000040;
              selfCollide_ = input.readBool();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000010) == 0x00000010)) {
          joint_ = java.util.Collections.unmodifiableList(joint_);
        }
        if (((mutable_bitField0_ & 0x00000020) == 0x00000020)) {
          link_ = java.util.Collections.unmodifiableList(link_);
        }
        if (((mutable_bitField0_ & 0x00000080) == 0x00000080)) {
          visual_ = java.util.Collections.unmodifiableList(visual_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.GzModel.internal_static_gazebo_msgs_Model_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.GzModel.internal_static_gazebo_msgs_Model_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.GzModel.Model.class, gazebo.msgs.GzModel.Model.Builder.class);
    }

    public static com.google.protobuf.Parser<Model> PARSER =
        new com.google.protobuf.AbstractParser<Model>() {
      public Model parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Model(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Model> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string name = 1;
    public static final int NAME_FIELD_NUMBER = 1;
    private java.lang.Object name_;
    /**
     * <code>required string name = 1;</code>
     */
    public boolean hasName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string name = 1;</code>
     */
    public java.lang.String getName() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          name_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      java.lang.Object ref = name_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        name_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 id = 2;
    public static final int ID_FIELD_NUMBER = 2;
    private int id_;
    /**
     * <code>optional uint32 id = 2;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 id = 2;</code>
     */
    public int getId() {
      return id_;
    }

    // optional bool is_static = 3;
    public static final int IS_STATIC_FIELD_NUMBER = 3;
    private boolean isStatic_;
    /**
     * <code>optional bool is_static = 3;</code>
     */
    public boolean hasIsStatic() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    /**
     * <code>optional bool is_static = 3;</code>
     */
    public boolean getIsStatic() {
      return isStatic_;
    }

    // optional .gazebo.msgs.Pose pose = 4;
    public static final int POSE_FIELD_NUMBER = 4;
    private gazebo.msgs.GzPose.Pose pose_;
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    public boolean hasPose() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    public gazebo.msgs.GzPose.Pose getPose() {
      return pose_;
    }
    /**
     * <code>optional .gazebo.msgs.Pose pose = 4;</code>
     */
    public gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder() {
      return pose_;
    }

    // repeated .gazebo.msgs.Joint joint = 5;
    public static final int JOINT_FIELD_NUMBER = 5;
    private java.util.List<gazebo.msgs.GzJoint.Joint> joint_;
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    public java.util.List<gazebo.msgs.GzJoint.Joint> getJointList() {
      return joint_;
    }
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    public java.util.List<? extends gazebo.msgs.GzJoint.JointOrBuilder> 
        getJointOrBuilderList() {
      return joint_;
    }
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    public int getJointCount() {
      return joint_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    public gazebo.msgs.GzJoint.Joint getJoint(int index) {
      return joint_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
     */
    public gazebo.msgs.GzJoint.JointOrBuilder getJointOrBuilder(
        int index) {
      return joint_.get(index);
    }

    // repeated .gazebo.msgs.Link link = 6;
    public static final int LINK_FIELD_NUMBER = 6;
    private java.util.List<gazebo.msgs.GzLink.Link> link_;
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    public java.util.List<gazebo.msgs.GzLink.Link> getLinkList() {
      return link_;
    }
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    public java.util.List<? extends gazebo.msgs.GzLink.LinkOrBuilder> 
        getLinkOrBuilderList() {
      return link_;
    }
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    public int getLinkCount() {
      return link_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    public gazebo.msgs.GzLink.Link getLink(int index) {
      return link_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Link link = 6;</code>
     */
    public gazebo.msgs.GzLink.LinkOrBuilder getLinkOrBuilder(
        int index) {
      return link_.get(index);
    }

    // optional bool deleted = 7;
    public static final int DELETED_FIELD_NUMBER = 7;
    private boolean deleted_;
    /**
     * <code>optional bool deleted = 7;</code>
     */
    public boolean hasDeleted() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    /**
     * <code>optional bool deleted = 7;</code>
     */
    public boolean getDeleted() {
      return deleted_;
    }

    // repeated .gazebo.msgs.Visual visual = 8;
    public static final int VISUAL_FIELD_NUMBER = 8;
    private java.util.List<gazebo.msgs.GzVisual.Visual> visual_;
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    public java.util.List<gazebo.msgs.GzVisual.Visual> getVisualList() {
      return visual_;
    }
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    public java.util.List<? extends gazebo.msgs.GzVisual.VisualOrBuilder> 
        getVisualOrBuilderList() {
      return visual_;
    }
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    public int getVisualCount() {
      return visual_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    public gazebo.msgs.GzVisual.Visual getVisual(int index) {
      return visual_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
     */
    public gazebo.msgs.GzVisual.VisualOrBuilder getVisualOrBuilder(
        int index) {
      return visual_.get(index);
    }

    // optional .gazebo.msgs.Vector3d scale = 9;
    public static final int SCALE_FIELD_NUMBER = 9;
    private gazebo.msgs.GzVector3d.Vector3d scale_;
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    public boolean hasScale() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    public gazebo.msgs.GzVector3d.Vector3d getScale() {
      return scale_;
    }
    /**
     * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
     */
    public gazebo.msgs.GzVector3d.Vector3dOrBuilder getScaleOrBuilder() {
      return scale_;
    }

    // optional bool self_collide = 10;
    public static final int SELF_COLLIDE_FIELD_NUMBER = 10;
    private boolean selfCollide_;
    /**
     * <code>optional bool self_collide = 10;</code>
     */
    public boolean hasSelfCollide() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    /**
     * <code>optional bool self_collide = 10;</code>
     */
    public boolean getSelfCollide() {
      return selfCollide_;
    }

    private void initFields() {
      name_ = "";
      id_ = 0;
      isStatic_ = false;
      pose_ = gazebo.msgs.GzPose.Pose.getDefaultInstance();
      joint_ = java.util.Collections.emptyList();
      link_ = java.util.Collections.emptyList();
      deleted_ = false;
      visual_ = java.util.Collections.emptyList();
      scale_ = gazebo.msgs.GzVector3d.Vector3d.getDefaultInstance();
      selfCollide_ = false;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (hasPose()) {
        if (!getPose().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getJointCount(); i++) {
        if (!getJoint(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getLinkCount(); i++) {
        if (!getLink(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getVisualCount(); i++) {
        if (!getVisual(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      if (hasScale()) {
        if (!getScale().isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeBool(3, isStatic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeMessage(4, pose_);
      }
      for (int i = 0; i < joint_.size(); i++) {
        output.writeMessage(5, joint_.get(i));
      }
      for (int i = 0; i < link_.size(); i++) {
        output.writeMessage(6, link_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeBool(7, deleted_);
      }
      for (int i = 0; i < visual_.size(); i++) {
        output.writeMessage(8, visual_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeMessage(9, scale_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBool(10, selfCollide_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, id_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, isStatic_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, pose_);
      }
      for (int i = 0; i < joint_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, joint_.get(i));
      }
      for (int i = 0; i < link_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, link_.get(i));
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(7, deleted_);
      }
      for (int i = 0; i < visual_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, visual_.get(i));
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, scale_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(10, selfCollide_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gazebo.msgs.GzModel.Model parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzModel.Model parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gazebo.msgs.GzModel.Model parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzModel.Model parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gazebo.msgs.GzModel.Model prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.Model}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gazebo.msgs.GzModel.ModelOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzModel.internal_static_gazebo_msgs_Model_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzModel.internal_static_gazebo_msgs_Model_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzModel.Model.class, gazebo.msgs.GzModel.Model.Builder.class);
      }

      // Construct using gazebo.msgs.GzModel.Model.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoseFieldBuilder();
          getJointFieldBuilder();
          getLinkFieldBuilder();
          getVisualFieldBuilder();
          getScaleFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        name_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        isStatic_ = false;
        bitField0_ = (bitField0_ & ~0x00000004);
        if (poseBuilder_ == null) {
          pose_ = gazebo.msgs.GzPose.Pose.getDefaultInstance();
        } else {
          poseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        if (jointBuilder_ == null) {
          joint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
        } else {
          jointBuilder_.clear();
        }
        if (linkBuilder_ == null) {
          link_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
        } else {
          linkBuilder_.clear();
        }
        deleted_ = false;
        bitField0_ = (bitField0_ & ~0x00000040);
        if (visualBuilder_ == null) {
          visual_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
        } else {
          visualBuilder_.clear();
        }
        if (scaleBuilder_ == null) {
          scale_ = gazebo.msgs.GzVector3d.Vector3d.getDefaultInstance();
        } else {
          scaleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        selfCollide_ = false;
        bitField0_ = (bitField0_ & ~0x00000200);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.GzModel.internal_static_gazebo_msgs_Model_descriptor;
      }

      public gazebo.msgs.GzModel.Model getDefaultInstanceForType() {
        return gazebo.msgs.GzModel.Model.getDefaultInstance();
      }

      public gazebo.msgs.GzModel.Model build() {
        gazebo.msgs.GzModel.Model result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gazebo.msgs.GzModel.Model buildPartial() {
        gazebo.msgs.GzModel.Model result = new gazebo.msgs.GzModel.Model(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.name_ = name_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.isStatic_ = isStatic_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        if (poseBuilder_ == null) {
          result.pose_ = pose_;
        } else {
          result.pose_ = poseBuilder_.build();
        }
        if (jointBuilder_ == null) {
          if (((bitField0_ & 0x00000010) == 0x00000010)) {
            joint_ = java.util.Collections.unmodifiableList(joint_);
            bitField0_ = (bitField0_ & ~0x00000010);
          }
          result.joint_ = joint_;
        } else {
          result.joint_ = jointBuilder_.build();
        }
        if (linkBuilder_ == null) {
          if (((bitField0_ & 0x00000020) == 0x00000020)) {
            link_ = java.util.Collections.unmodifiableList(link_);
            bitField0_ = (bitField0_ & ~0x00000020);
          }
          result.link_ = link_;
        } else {
          result.link_ = linkBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000010;
        }
        result.deleted_ = deleted_;
        if (visualBuilder_ == null) {
          if (((bitField0_ & 0x00000080) == 0x00000080)) {
            visual_ = java.util.Collections.unmodifiableList(visual_);
            bitField0_ = (bitField0_ & ~0x00000080);
          }
          result.visual_ = visual_;
        } else {
          result.visual_ = visualBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000100) == 0x00000100)) {
          to_bitField0_ |= 0x00000020;
        }
        if (scaleBuilder_ == null) {
          result.scale_ = scale_;
        } else {
          result.scale_ = scaleBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000200) == 0x00000200)) {
          to_bitField0_ |= 0x00000040;
        }
        result.selfCollide_ = selfCollide_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.GzModel.Model) {
          return mergeFrom((gazebo.msgs.GzModel.Model)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.GzModel.Model other) {
        if (other == gazebo.msgs.GzModel.Model.getDefaultInstance()) return this;
        if (other.hasName()) {
          bitField0_ |= 0x00000001;
          name_ = other.name_;
          onChanged();
        }
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasIsStatic()) {
          setIsStatic(other.getIsStatic());
        }
        if (other.hasPose()) {
          mergePose(other.getPose());
        }
        if (jointBuilder_ == null) {
          if (!other.joint_.isEmpty()) {
            if (joint_.isEmpty()) {
              joint_ = other.joint_;
              bitField0_ = (bitField0_ & ~0x00000010);
            } else {
              ensureJointIsMutable();
              joint_.addAll(other.joint_);
            }
            onChanged();
          }
        } else {
          if (!other.joint_.isEmpty()) {
            if (jointBuilder_.isEmpty()) {
              jointBuilder_.dispose();
              jointBuilder_ = null;
              joint_ = other.joint_;
              bitField0_ = (bitField0_ & ~0x00000010);
              jointBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getJointFieldBuilder() : null;
            } else {
              jointBuilder_.addAllMessages(other.joint_);
            }
          }
        }
        if (linkBuilder_ == null) {
          if (!other.link_.isEmpty()) {
            if (link_.isEmpty()) {
              link_ = other.link_;
              bitField0_ = (bitField0_ & ~0x00000020);
            } else {
              ensureLinkIsMutable();
              link_.addAll(other.link_);
            }
            onChanged();
          }
        } else {
          if (!other.link_.isEmpty()) {
            if (linkBuilder_.isEmpty()) {
              linkBuilder_.dispose();
              linkBuilder_ = null;
              link_ = other.link_;
              bitField0_ = (bitField0_ & ~0x00000020);
              linkBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getLinkFieldBuilder() : null;
            } else {
              linkBuilder_.addAllMessages(other.link_);
            }
          }
        }
        if (other.hasDeleted()) {
          setDeleted(other.getDeleted());
        }
        if (visualBuilder_ == null) {
          if (!other.visual_.isEmpty()) {
            if (visual_.isEmpty()) {
              visual_ = other.visual_;
              bitField0_ = (bitField0_ & ~0x00000080);
            } else {
              ensureVisualIsMutable();
              visual_.addAll(other.visual_);
            }
            onChanged();
          }
        } else {
          if (!other.visual_.isEmpty()) {
            if (visualBuilder_.isEmpty()) {
              visualBuilder_.dispose();
              visualBuilder_ = null;
              visual_ = other.visual_;
              bitField0_ = (bitField0_ & ~0x00000080);
              visualBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getVisualFieldBuilder() : null;
            } else {
              visualBuilder_.addAllMessages(other.visual_);
            }
          }
        }
        if (other.hasScale()) {
          mergeScale(other.getScale());
        }
        if (other.hasSelfCollide()) {
          setSelfCollide(other.getSelfCollide());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasName()) {
          
          return false;
        }
        if (hasPose()) {
          if (!getPose().isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getJointCount(); i++) {
          if (!getJoint(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getLinkCount(); i++) {
          if (!getLink(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getVisualCount(); i++) {
          if (!getVisual(i).isInitialized()) {
            
            return false;
          }
        }
        if (hasScale()) {
          if (!getScale().isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.GzModel.Model parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.GzModel.Model) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string name = 1;
      private java.lang.Object name_ = "";
      /**
       * <code>required string name = 1;</code>
       */
      public boolean hasName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string name = 1;</code>
       */
      public java.lang.String getName() {
        java.lang.Object ref = name_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          name_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getNameBytes() {
        java.lang.Object ref = name_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          name_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder clearName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        name_ = getDefaultInstance().getName();
        onChanged();
        return this;
      }
      /**
       * <code>required string name = 1;</code>
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        name_ = value;
        onChanged();
        return this;
      }

      // optional uint32 id = 2;
      private int id_ ;
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public int getId() {
        return id_;
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public Builder setId(int value) {
        bitField0_ |= 0x00000002;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 id = 2;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        id_ = 0;
        onChanged();
        return this;
      }

      // optional bool is_static = 3;
      private boolean isStatic_ ;
      /**
       * <code>optional bool is_static = 3;</code>
       */
      public boolean hasIsStatic() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      /**
       * <code>optional bool is_static = 3;</code>
       */
      public boolean getIsStatic() {
        return isStatic_;
      }
      /**
       * <code>optional bool is_static = 3;</code>
       */
      public Builder setIsStatic(boolean value) {
        bitField0_ |= 0x00000004;
        isStatic_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool is_static = 3;</code>
       */
      public Builder clearIsStatic() {
        bitField0_ = (bitField0_ & ~0x00000004);
        isStatic_ = false;
        onChanged();
        return this;
      }

      // optional .gazebo.msgs.Pose pose = 4;
      private gazebo.msgs.GzPose.Pose pose_ = gazebo.msgs.GzPose.Pose.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder> poseBuilder_;
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public boolean hasPose() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public gazebo.msgs.GzPose.Pose getPose() {
        if (poseBuilder_ == null) {
          return pose_;
        } else {
          return poseBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public Builder setPose(gazebo.msgs.GzPose.Pose value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          pose_ = value;
          onChanged();
        } else {
          poseBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public Builder setPose(
          gazebo.msgs.GzPose.Pose.Builder builderForValue) {
        if (poseBuilder_ == null) {
          pose_ = builderForValue.build();
          onChanged();
        } else {
          poseBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public Builder mergePose(gazebo.msgs.GzPose.Pose value) {
        if (poseBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008) &&
              pose_ != gazebo.msgs.GzPose.Pose.getDefaultInstance()) {
            pose_ =
              gazebo.msgs.GzPose.Pose.newBuilder(pose_).mergeFrom(value).buildPartial();
          } else {
            pose_ = value;
          }
          onChanged();
        } else {
          poseBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000008;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public Builder clearPose() {
        if (poseBuilder_ == null) {
          pose_ = gazebo.msgs.GzPose.Pose.getDefaultInstance();
          onChanged();
        } else {
          poseBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000008);
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public gazebo.msgs.GzPose.Pose.Builder getPoseBuilder() {
        bitField0_ |= 0x00000008;
        onChanged();
        return getPoseFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      public gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder() {
        if (poseBuilder_ != null) {
          return poseBuilder_.getMessageOrBuilder();
        } else {
          return pose_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.Pose pose = 4;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder> 
          getPoseFieldBuilder() {
        if (poseBuilder_ == null) {
          poseBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder>(
                  pose_,
                  getParentForChildren(),
                  isClean());
          pose_ = null;
        }
        return poseBuilder_;
      }

      // repeated .gazebo.msgs.Joint joint = 5;
      private java.util.List<gazebo.msgs.GzJoint.Joint> joint_ =
        java.util.Collections.emptyList();
      private void ensureJointIsMutable() {
        if (!((bitField0_ & 0x00000010) == 0x00000010)) {
          joint_ = new java.util.ArrayList<gazebo.msgs.GzJoint.Joint>(joint_);
          bitField0_ |= 0x00000010;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzJoint.Joint, gazebo.msgs.GzJoint.Joint.Builder, gazebo.msgs.GzJoint.JointOrBuilder> jointBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public java.util.List<gazebo.msgs.GzJoint.Joint> getJointList() {
        if (jointBuilder_ == null) {
          return java.util.Collections.unmodifiableList(joint_);
        } else {
          return jointBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public int getJointCount() {
        if (jointBuilder_ == null) {
          return joint_.size();
        } else {
          return jointBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public gazebo.msgs.GzJoint.Joint getJoint(int index) {
        if (jointBuilder_ == null) {
          return joint_.get(index);
        } else {
          return jointBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder setJoint(
          int index, gazebo.msgs.GzJoint.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.set(index, value);
          onChanged();
        } else {
          jointBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder setJoint(
          int index, gazebo.msgs.GzJoint.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.set(index, builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder addJoint(gazebo.msgs.GzJoint.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.add(value);
          onChanged();
        } else {
          jointBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder addJoint(
          int index, gazebo.msgs.GzJoint.Joint value) {
        if (jointBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureJointIsMutable();
          joint_.add(index, value);
          onChanged();
        } else {
          jointBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder addJoint(
          gazebo.msgs.GzJoint.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.add(builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder addJoint(
          int index, gazebo.msgs.GzJoint.Joint.Builder builderForValue) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.add(index, builderForValue.build());
          onChanged();
        } else {
          jointBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder addAllJoint(
          java.lang.Iterable<? extends gazebo.msgs.GzJoint.Joint> values) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          super.addAll(values, joint_);
          onChanged();
        } else {
          jointBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder clearJoint() {
        if (jointBuilder_ == null) {
          joint_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000010);
          onChanged();
        } else {
          jointBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public Builder removeJoint(int index) {
        if (jointBuilder_ == null) {
          ensureJointIsMutable();
          joint_.remove(index);
          onChanged();
        } else {
          jointBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public gazebo.msgs.GzJoint.Joint.Builder getJointBuilder(
          int index) {
        return getJointFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public gazebo.msgs.GzJoint.JointOrBuilder getJointOrBuilder(
          int index) {
        if (jointBuilder_ == null) {
          return joint_.get(index);  } else {
          return jointBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public java.util.List<? extends gazebo.msgs.GzJoint.JointOrBuilder> 
           getJointOrBuilderList() {
        if (jointBuilder_ != null) {
          return jointBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(joint_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public gazebo.msgs.GzJoint.Joint.Builder addJointBuilder() {
        return getJointFieldBuilder().addBuilder(
            gazebo.msgs.GzJoint.Joint.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public gazebo.msgs.GzJoint.Joint.Builder addJointBuilder(
          int index) {
        return getJointFieldBuilder().addBuilder(
            index, gazebo.msgs.GzJoint.Joint.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Joint joint = 5;</code>
       */
      public java.util.List<gazebo.msgs.GzJoint.Joint.Builder> 
           getJointBuilderList() {
        return getJointFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzJoint.Joint, gazebo.msgs.GzJoint.Joint.Builder, gazebo.msgs.GzJoint.JointOrBuilder> 
          getJointFieldBuilder() {
        if (jointBuilder_ == null) {
          jointBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gazebo.msgs.GzJoint.Joint, gazebo.msgs.GzJoint.Joint.Builder, gazebo.msgs.GzJoint.JointOrBuilder>(
                  joint_,
                  ((bitField0_ & 0x00000010) == 0x00000010),
                  getParentForChildren(),
                  isClean());
          joint_ = null;
        }
        return jointBuilder_;
      }

      // repeated .gazebo.msgs.Link link = 6;
      private java.util.List<gazebo.msgs.GzLink.Link> link_ =
        java.util.Collections.emptyList();
      private void ensureLinkIsMutable() {
        if (!((bitField0_ & 0x00000020) == 0x00000020)) {
          link_ = new java.util.ArrayList<gazebo.msgs.GzLink.Link>(link_);
          bitField0_ |= 0x00000020;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzLink.Link, gazebo.msgs.GzLink.Link.Builder, gazebo.msgs.GzLink.LinkOrBuilder> linkBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public java.util.List<gazebo.msgs.GzLink.Link> getLinkList() {
        if (linkBuilder_ == null) {
          return java.util.Collections.unmodifiableList(link_);
        } else {
          return linkBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public int getLinkCount() {
        if (linkBuilder_ == null) {
          return link_.size();
        } else {
          return linkBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public gazebo.msgs.GzLink.Link getLink(int index) {
        if (linkBuilder_ == null) {
          return link_.get(index);
        } else {
          return linkBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder setLink(
          int index, gazebo.msgs.GzLink.Link value) {
        if (linkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkIsMutable();
          link_.set(index, value);
          onChanged();
        } else {
          linkBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder setLink(
          int index, gazebo.msgs.GzLink.Link.Builder builderForValue) {
        if (linkBuilder_ == null) {
          ensureLinkIsMutable();
          link_.set(index, builderForValue.build());
          onChanged();
        } else {
          linkBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder addLink(gazebo.msgs.GzLink.Link value) {
        if (linkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkIsMutable();
          link_.add(value);
          onChanged();
        } else {
          linkBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder addLink(
          int index, gazebo.msgs.GzLink.Link value) {
        if (linkBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureLinkIsMutable();
          link_.add(index, value);
          onChanged();
        } else {
          linkBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder addLink(
          gazebo.msgs.GzLink.Link.Builder builderForValue) {
        if (linkBuilder_ == null) {
          ensureLinkIsMutable();
          link_.add(builderForValue.build());
          onChanged();
        } else {
          linkBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder addLink(
          int index, gazebo.msgs.GzLink.Link.Builder builderForValue) {
        if (linkBuilder_ == null) {
          ensureLinkIsMutable();
          link_.add(index, builderForValue.build());
          onChanged();
        } else {
          linkBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder addAllLink(
          java.lang.Iterable<? extends gazebo.msgs.GzLink.Link> values) {
        if (linkBuilder_ == null) {
          ensureLinkIsMutable();
          super.addAll(values, link_);
          onChanged();
        } else {
          linkBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder clearLink() {
        if (linkBuilder_ == null) {
          link_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000020);
          onChanged();
        } else {
          linkBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public Builder removeLink(int index) {
        if (linkBuilder_ == null) {
          ensureLinkIsMutable();
          link_.remove(index);
          onChanged();
        } else {
          linkBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public gazebo.msgs.GzLink.Link.Builder getLinkBuilder(
          int index) {
        return getLinkFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public gazebo.msgs.GzLink.LinkOrBuilder getLinkOrBuilder(
          int index) {
        if (linkBuilder_ == null) {
          return link_.get(index);  } else {
          return linkBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public java.util.List<? extends gazebo.msgs.GzLink.LinkOrBuilder> 
           getLinkOrBuilderList() {
        if (linkBuilder_ != null) {
          return linkBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(link_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public gazebo.msgs.GzLink.Link.Builder addLinkBuilder() {
        return getLinkFieldBuilder().addBuilder(
            gazebo.msgs.GzLink.Link.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public gazebo.msgs.GzLink.Link.Builder addLinkBuilder(
          int index) {
        return getLinkFieldBuilder().addBuilder(
            index, gazebo.msgs.GzLink.Link.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Link link = 6;</code>
       */
      public java.util.List<gazebo.msgs.GzLink.Link.Builder> 
           getLinkBuilderList() {
        return getLinkFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzLink.Link, gazebo.msgs.GzLink.Link.Builder, gazebo.msgs.GzLink.LinkOrBuilder> 
          getLinkFieldBuilder() {
        if (linkBuilder_ == null) {
          linkBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gazebo.msgs.GzLink.Link, gazebo.msgs.GzLink.Link.Builder, gazebo.msgs.GzLink.LinkOrBuilder>(
                  link_,
                  ((bitField0_ & 0x00000020) == 0x00000020),
                  getParentForChildren(),
                  isClean());
          link_ = null;
        }
        return linkBuilder_;
      }

      // optional bool deleted = 7;
      private boolean deleted_ ;
      /**
       * <code>optional bool deleted = 7;</code>
       */
      public boolean hasDeleted() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      /**
       * <code>optional bool deleted = 7;</code>
       */
      public boolean getDeleted() {
        return deleted_;
      }
      /**
       * <code>optional bool deleted = 7;</code>
       */
      public Builder setDeleted(boolean value) {
        bitField0_ |= 0x00000040;
        deleted_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool deleted = 7;</code>
       */
      public Builder clearDeleted() {
        bitField0_ = (bitField0_ & ~0x00000040);
        deleted_ = false;
        onChanged();
        return this;
      }

      // repeated .gazebo.msgs.Visual visual = 8;
      private java.util.List<gazebo.msgs.GzVisual.Visual> visual_ =
        java.util.Collections.emptyList();
      private void ensureVisualIsMutable() {
        if (!((bitField0_ & 0x00000080) == 0x00000080)) {
          visual_ = new java.util.ArrayList<gazebo.msgs.GzVisual.Visual>(visual_);
          bitField0_ |= 0x00000080;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzVisual.Visual, gazebo.msgs.GzVisual.Visual.Builder, gazebo.msgs.GzVisual.VisualOrBuilder> visualBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public java.util.List<gazebo.msgs.GzVisual.Visual> getVisualList() {
        if (visualBuilder_ == null) {
          return java.util.Collections.unmodifiableList(visual_);
        } else {
          return visualBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public int getVisualCount() {
        if (visualBuilder_ == null) {
          return visual_.size();
        } else {
          return visualBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public gazebo.msgs.GzVisual.Visual getVisual(int index) {
        if (visualBuilder_ == null) {
          return visual_.get(index);
        } else {
          return visualBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder setVisual(
          int index, gazebo.msgs.GzVisual.Visual value) {
        if (visualBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVisualIsMutable();
          visual_.set(index, value);
          onChanged();
        } else {
          visualBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder setVisual(
          int index, gazebo.msgs.GzVisual.Visual.Builder builderForValue) {
        if (visualBuilder_ == null) {
          ensureVisualIsMutable();
          visual_.set(index, builderForValue.build());
          onChanged();
        } else {
          visualBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder addVisual(gazebo.msgs.GzVisual.Visual value) {
        if (visualBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVisualIsMutable();
          visual_.add(value);
          onChanged();
        } else {
          visualBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder addVisual(
          int index, gazebo.msgs.GzVisual.Visual value) {
        if (visualBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureVisualIsMutable();
          visual_.add(index, value);
          onChanged();
        } else {
          visualBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder addVisual(
          gazebo.msgs.GzVisual.Visual.Builder builderForValue) {
        if (visualBuilder_ == null) {
          ensureVisualIsMutable();
          visual_.add(builderForValue.build());
          onChanged();
        } else {
          visualBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder addVisual(
          int index, gazebo.msgs.GzVisual.Visual.Builder builderForValue) {
        if (visualBuilder_ == null) {
          ensureVisualIsMutable();
          visual_.add(index, builderForValue.build());
          onChanged();
        } else {
          visualBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder addAllVisual(
          java.lang.Iterable<? extends gazebo.msgs.GzVisual.Visual> values) {
        if (visualBuilder_ == null) {
          ensureVisualIsMutable();
          super.addAll(values, visual_);
          onChanged();
        } else {
          visualBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder clearVisual() {
        if (visualBuilder_ == null) {
          visual_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000080);
          onChanged();
        } else {
          visualBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public Builder removeVisual(int index) {
        if (visualBuilder_ == null) {
          ensureVisualIsMutable();
          visual_.remove(index);
          onChanged();
        } else {
          visualBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public gazebo.msgs.GzVisual.Visual.Builder getVisualBuilder(
          int index) {
        return getVisualFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public gazebo.msgs.GzVisual.VisualOrBuilder getVisualOrBuilder(
          int index) {
        if (visualBuilder_ == null) {
          return visual_.get(index);  } else {
          return visualBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public java.util.List<? extends gazebo.msgs.GzVisual.VisualOrBuilder> 
           getVisualOrBuilderList() {
        if (visualBuilder_ != null) {
          return visualBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(visual_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public gazebo.msgs.GzVisual.Visual.Builder addVisualBuilder() {
        return getVisualFieldBuilder().addBuilder(
            gazebo.msgs.GzVisual.Visual.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public gazebo.msgs.GzVisual.Visual.Builder addVisualBuilder(
          int index) {
        return getVisualFieldBuilder().addBuilder(
            index, gazebo.msgs.GzVisual.Visual.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Visual visual = 8;</code>
       */
      public java.util.List<gazebo.msgs.GzVisual.Visual.Builder> 
           getVisualBuilderList() {
        return getVisualFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzVisual.Visual, gazebo.msgs.GzVisual.Visual.Builder, gazebo.msgs.GzVisual.VisualOrBuilder> 
          getVisualFieldBuilder() {
        if (visualBuilder_ == null) {
          visualBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gazebo.msgs.GzVisual.Visual, gazebo.msgs.GzVisual.Visual.Builder, gazebo.msgs.GzVisual.VisualOrBuilder>(
                  visual_,
                  ((bitField0_ & 0x00000080) == 0x00000080),
                  getParentForChildren(),
                  isClean());
          visual_ = null;
        }
        return visualBuilder_;
      }

      // optional .gazebo.msgs.Vector3d scale = 9;
      private gazebo.msgs.GzVector3d.Vector3d scale_ = gazebo.msgs.GzVector3d.Vector3d.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzVector3d.Vector3d, gazebo.msgs.GzVector3d.Vector3d.Builder, gazebo.msgs.GzVector3d.Vector3dOrBuilder> scaleBuilder_;
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public boolean hasScale() {
        return ((bitField0_ & 0x00000100) == 0x00000100);
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public gazebo.msgs.GzVector3d.Vector3d getScale() {
        if (scaleBuilder_ == null) {
          return scale_;
        } else {
          return scaleBuilder_.getMessage();
        }
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public Builder setScale(gazebo.msgs.GzVector3d.Vector3d value) {
        if (scaleBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          scale_ = value;
          onChanged();
        } else {
          scaleBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public Builder setScale(
          gazebo.msgs.GzVector3d.Vector3d.Builder builderForValue) {
        if (scaleBuilder_ == null) {
          scale_ = builderForValue.build();
          onChanged();
        } else {
          scaleBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public Builder mergeScale(gazebo.msgs.GzVector3d.Vector3d value) {
        if (scaleBuilder_ == null) {
          if (((bitField0_ & 0x00000100) == 0x00000100) &&
              scale_ != gazebo.msgs.GzVector3d.Vector3d.getDefaultInstance()) {
            scale_ =
              gazebo.msgs.GzVector3d.Vector3d.newBuilder(scale_).mergeFrom(value).buildPartial();
          } else {
            scale_ = value;
          }
          onChanged();
        } else {
          scaleBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000100;
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public Builder clearScale() {
        if (scaleBuilder_ == null) {
          scale_ = gazebo.msgs.GzVector3d.Vector3d.getDefaultInstance();
          onChanged();
        } else {
          scaleBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000100);
        return this;
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public gazebo.msgs.GzVector3d.Vector3d.Builder getScaleBuilder() {
        bitField0_ |= 0x00000100;
        onChanged();
        return getScaleFieldBuilder().getBuilder();
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      public gazebo.msgs.GzVector3d.Vector3dOrBuilder getScaleOrBuilder() {
        if (scaleBuilder_ != null) {
          return scaleBuilder_.getMessageOrBuilder();
        } else {
          return scale_;
        }
      }
      /**
       * <code>optional .gazebo.msgs.Vector3d scale = 9;</code>
       */
      private com.google.protobuf.SingleFieldBuilder<
          gazebo.msgs.GzVector3d.Vector3d, gazebo.msgs.GzVector3d.Vector3d.Builder, gazebo.msgs.GzVector3d.Vector3dOrBuilder> 
          getScaleFieldBuilder() {
        if (scaleBuilder_ == null) {
          scaleBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              gazebo.msgs.GzVector3d.Vector3d, gazebo.msgs.GzVector3d.Vector3d.Builder, gazebo.msgs.GzVector3d.Vector3dOrBuilder>(
                  scale_,
                  getParentForChildren(),
                  isClean());
          scale_ = null;
        }
        return scaleBuilder_;
      }

      // optional bool self_collide = 10;
      private boolean selfCollide_ ;
      /**
       * <code>optional bool self_collide = 10;</code>
       */
      public boolean hasSelfCollide() {
        return ((bitField0_ & 0x00000200) == 0x00000200);
      }
      /**
       * <code>optional bool self_collide = 10;</code>
       */
      public boolean getSelfCollide() {
        return selfCollide_;
      }
      /**
       * <code>optional bool self_collide = 10;</code>
       */
      public Builder setSelfCollide(boolean value) {
        bitField0_ |= 0x00000200;
        selfCollide_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional bool self_collide = 10;</code>
       */
      public Builder clearSelfCollide() {
        bitField0_ = (bitField0_ & ~0x00000200);
        selfCollide_ = false;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.Model)
    }

    static {
      defaultInstance = new Model(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.Model)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_Model_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_Model_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\013model.proto\022\013gazebo.msgs\032\013joint.proto\032" +
      "\nlink.proto\032\npose.proto\032\014visual.proto\032\016v" +
      "ector3d.proto\"\213\002\n\005Model\022\014\n\004name\030\001 \002(\t\022\n\n" +
      "\002id\030\002 \001(\r\022\021\n\tis_static\030\003 \001(\010\022\037\n\004pose\030\004 \001" +
      "(\0132\021.gazebo.msgs.Pose\022!\n\005joint\030\005 \003(\0132\022.g" +
      "azebo.msgs.Joint\022\037\n\004link\030\006 \003(\0132\021.gazebo." +
      "msgs.Link\022\017\n\007deleted\030\007 \001(\010\022#\n\006visual\030\010 \003" +
      "(\0132\023.gazebo.msgs.Visual\022$\n\005scale\030\t \001(\0132\025" +
      ".gazebo.msgs.Vector3d\022\024\n\014self_collide\030\n " +
      "\001(\010B\tB\007GzModel"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gazebo_msgs_Model_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gazebo_msgs_Model_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_Model_descriptor,
              new java.lang.String[] { "Name", "Id", "IsStatic", "Pose", "Joint", "Link", "Deleted", "Visual", "Scale", "SelfCollide", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GzJoint.getDescriptor(),
          gazebo.msgs.GzLink.getDescriptor(),
          gazebo.msgs.GzPose.getDescriptor(),
          gazebo.msgs.GzVisual.getDescriptor(),
          gazebo.msgs.GzVector3d.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
