// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: pose_animation.proto

package gazebo.msgs;

public final class GzPoseAnimation {
  private GzPoseAnimation() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface PoseAnimationOrBuilder
      extends com.google.protobuf.MessageOrBuilder {

    // required string model_name = 1;
    /**
     * <code>required string model_name = 1;</code>
     */
    boolean hasModelName();
    /**
     * <code>required string model_name = 1;</code>
     */
    java.lang.String getModelName();
    /**
     * <code>required string model_name = 1;</code>
     */
    com.google.protobuf.ByteString
        getModelNameBytes();

    // optional uint32 model_id = 2;
    /**
     * <code>optional uint32 model_id = 2;</code>
     */
    boolean hasModelId();
    /**
     * <code>optional uint32 model_id = 2;</code>
     */
    int getModelId();

    // repeated .gazebo.msgs.Pose pose = 3;
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    java.util.List<gazebo.msgs.GzPose.Pose> 
        getPoseList();
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    gazebo.msgs.GzPose.Pose getPose(int index);
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    int getPoseCount();
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    java.util.List<? extends gazebo.msgs.GzPose.PoseOrBuilder> 
        getPoseOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder(
        int index);

    // repeated .gazebo.msgs.Time time = 4;
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    java.util.List<gazebo.msgs.GzTime.Time> 
        getTimeList();
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    gazebo.msgs.GzTime.Time getTime(int index);
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    int getTimeCount();
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    java.util.List<? extends gazebo.msgs.GzTime.TimeOrBuilder> 
        getTimeOrBuilderList();
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    gazebo.msgs.GzTime.TimeOrBuilder getTimeOrBuilder(
        int index);
  }
  /**
   * Protobuf type {@code gazebo.msgs.PoseAnimation}
   */
  public static final class PoseAnimation extends
      com.google.protobuf.GeneratedMessage
      implements PoseAnimationOrBuilder {
    // Use PoseAnimation.newBuilder() to construct.
    private PoseAnimation(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private PoseAnimation(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final PoseAnimation defaultInstance;
    public static PoseAnimation getDefaultInstance() {
      return defaultInstance;
    }

    public PoseAnimation getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private PoseAnimation(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 10: {
              bitField0_ |= 0x00000001;
              modelName_ = input.readBytes();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              modelId_ = input.readUInt32();
              break;
            }
            case 26: {
              if (!((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
                pose_ = new java.util.ArrayList<gazebo.msgs.GzPose.Pose>();
                mutable_bitField0_ |= 0x00000004;
              }
              pose_.add(input.readMessage(gazebo.msgs.GzPose.Pose.PARSER, extensionRegistry));
              break;
            }
            case 34: {
              if (!((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
                time_ = new java.util.ArrayList<gazebo.msgs.GzTime.Time>();
                mutable_bitField0_ |= 0x00000008;
              }
              time_.add(input.readMessage(gazebo.msgs.GzTime.Time.PARSER, extensionRegistry));
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        if (((mutable_bitField0_ & 0x00000004) == 0x00000004)) {
          pose_ = java.util.Collections.unmodifiableList(pose_);
        }
        if (((mutable_bitField0_ & 0x00000008) == 0x00000008)) {
          time_ = java.util.Collections.unmodifiableList(time_);
        }
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return gazebo.msgs.GzPoseAnimation.internal_static_gazebo_msgs_PoseAnimation_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return gazebo.msgs.GzPoseAnimation.internal_static_gazebo_msgs_PoseAnimation_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              gazebo.msgs.GzPoseAnimation.PoseAnimation.class, gazebo.msgs.GzPoseAnimation.PoseAnimation.Builder.class);
    }

    public static com.google.protobuf.Parser<PoseAnimation> PARSER =
        new com.google.protobuf.AbstractParser<PoseAnimation>() {
      public PoseAnimation parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new PoseAnimation(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<PoseAnimation> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    // required string model_name = 1;
    public static final int MODEL_NAME_FIELD_NUMBER = 1;
    private java.lang.Object modelName_;
    /**
     * <code>required string model_name = 1;</code>
     */
    public boolean hasModelName() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required string model_name = 1;</code>
     */
    public java.lang.String getModelName() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        if (bs.isValidUtf8()) {
          modelName_ = s;
        }
        return s;
      }
    }
    /**
     * <code>required string model_name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getModelNameBytes() {
      java.lang.Object ref = modelName_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        modelName_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    // optional uint32 model_id = 2;
    public static final int MODEL_ID_FIELD_NUMBER = 2;
    private int modelId_;
    /**
     * <code>optional uint32 model_id = 2;</code>
     */
    public boolean hasModelId() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>optional uint32 model_id = 2;</code>
     */
    public int getModelId() {
      return modelId_;
    }

    // repeated .gazebo.msgs.Pose pose = 3;
    public static final int POSE_FIELD_NUMBER = 3;
    private java.util.List<gazebo.msgs.GzPose.Pose> pose_;
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    public java.util.List<gazebo.msgs.GzPose.Pose> getPoseList() {
      return pose_;
    }
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    public java.util.List<? extends gazebo.msgs.GzPose.PoseOrBuilder> 
        getPoseOrBuilderList() {
      return pose_;
    }
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    public int getPoseCount() {
      return pose_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    public gazebo.msgs.GzPose.Pose getPose(int index) {
      return pose_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
     */
    public gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder(
        int index) {
      return pose_.get(index);
    }

    // repeated .gazebo.msgs.Time time = 4;
    public static final int TIME_FIELD_NUMBER = 4;
    private java.util.List<gazebo.msgs.GzTime.Time> time_;
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    public java.util.List<gazebo.msgs.GzTime.Time> getTimeList() {
      return time_;
    }
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    public java.util.List<? extends gazebo.msgs.GzTime.TimeOrBuilder> 
        getTimeOrBuilderList() {
      return time_;
    }
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    public int getTimeCount() {
      return time_.size();
    }
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    public gazebo.msgs.GzTime.Time getTime(int index) {
      return time_.get(index);
    }
    /**
     * <code>repeated .gazebo.msgs.Time time = 4;</code>
     */
    public gazebo.msgs.GzTime.TimeOrBuilder getTimeOrBuilder(
        int index) {
      return time_.get(index);
    }

    private void initFields() {
      modelName_ = "";
      modelId_ = 0;
      pose_ = java.util.Collections.emptyList();
      time_ = java.util.Collections.emptyList();
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;

      if (!hasModelName()) {
        memoizedIsInitialized = 0;
        return false;
      }
      for (int i = 0; i < getPoseCount(); i++) {
        if (!getPose(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      for (int i = 0; i < getTimeCount(); i++) {
        if (!getTime(i).isInitialized()) {
          memoizedIsInitialized = 0;
          return false;
        }
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(1, getModelNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeUInt32(2, modelId_);
      }
      for (int i = 0; i < pose_.size(); i++) {
        output.writeMessage(3, pose_.get(i));
      }
      for (int i = 0; i < time_.size(); i++) {
        output.writeMessage(4, time_.get(i));
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(1, getModelNameBytes());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeUInt32Size(2, modelId_);
      }
      for (int i = 0; i < pose_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, pose_.get(i));
      }
      for (int i = 0; i < time_.size(); i++) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, time_.get(i));
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static gazebo.msgs.GzPoseAnimation.PoseAnimation parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(gazebo.msgs.GzPoseAnimation.PoseAnimation prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code gazebo.msgs.PoseAnimation}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements gazebo.msgs.GzPoseAnimation.PoseAnimationOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return gazebo.msgs.GzPoseAnimation.internal_static_gazebo_msgs_PoseAnimation_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return gazebo.msgs.GzPoseAnimation.internal_static_gazebo_msgs_PoseAnimation_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                gazebo.msgs.GzPoseAnimation.PoseAnimation.class, gazebo.msgs.GzPoseAnimation.PoseAnimation.Builder.class);
      }

      // Construct using gazebo.msgs.GzPoseAnimation.PoseAnimation.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getPoseFieldBuilder();
          getTimeFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        modelName_ = "";
        bitField0_ = (bitField0_ & ~0x00000001);
        modelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000002);
        if (poseBuilder_ == null) {
          pose_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
        } else {
          poseBuilder_.clear();
        }
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
        } else {
          timeBuilder_.clear();
        }
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return gazebo.msgs.GzPoseAnimation.internal_static_gazebo_msgs_PoseAnimation_descriptor;
      }

      public gazebo.msgs.GzPoseAnimation.PoseAnimation getDefaultInstanceForType() {
        return gazebo.msgs.GzPoseAnimation.PoseAnimation.getDefaultInstance();
      }

      public gazebo.msgs.GzPoseAnimation.PoseAnimation build() {
        gazebo.msgs.GzPoseAnimation.PoseAnimation result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public gazebo.msgs.GzPoseAnimation.PoseAnimation buildPartial() {
        gazebo.msgs.GzPoseAnimation.PoseAnimation result = new gazebo.msgs.GzPoseAnimation.PoseAnimation(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.modelName_ = modelName_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.modelId_ = modelId_;
        if (poseBuilder_ == null) {
          if (((bitField0_ & 0x00000004) == 0x00000004)) {
            pose_ = java.util.Collections.unmodifiableList(pose_);
            bitField0_ = (bitField0_ & ~0x00000004);
          }
          result.pose_ = pose_;
        } else {
          result.pose_ = poseBuilder_.build();
        }
        if (timeBuilder_ == null) {
          if (((bitField0_ & 0x00000008) == 0x00000008)) {
            time_ = java.util.Collections.unmodifiableList(time_);
            bitField0_ = (bitField0_ & ~0x00000008);
          }
          result.time_ = time_;
        } else {
          result.time_ = timeBuilder_.build();
        }
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof gazebo.msgs.GzPoseAnimation.PoseAnimation) {
          return mergeFrom((gazebo.msgs.GzPoseAnimation.PoseAnimation)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(gazebo.msgs.GzPoseAnimation.PoseAnimation other) {
        if (other == gazebo.msgs.GzPoseAnimation.PoseAnimation.getDefaultInstance()) return this;
        if (other.hasModelName()) {
          bitField0_ |= 0x00000001;
          modelName_ = other.modelName_;
          onChanged();
        }
        if (other.hasModelId()) {
          setModelId(other.getModelId());
        }
        if (poseBuilder_ == null) {
          if (!other.pose_.isEmpty()) {
            if (pose_.isEmpty()) {
              pose_ = other.pose_;
              bitField0_ = (bitField0_ & ~0x00000004);
            } else {
              ensurePoseIsMutable();
              pose_.addAll(other.pose_);
            }
            onChanged();
          }
        } else {
          if (!other.pose_.isEmpty()) {
            if (poseBuilder_.isEmpty()) {
              poseBuilder_.dispose();
              poseBuilder_ = null;
              pose_ = other.pose_;
              bitField0_ = (bitField0_ & ~0x00000004);
              poseBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getPoseFieldBuilder() : null;
            } else {
              poseBuilder_.addAllMessages(other.pose_);
            }
          }
        }
        if (timeBuilder_ == null) {
          if (!other.time_.isEmpty()) {
            if (time_.isEmpty()) {
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000008);
            } else {
              ensureTimeIsMutable();
              time_.addAll(other.time_);
            }
            onChanged();
          }
        } else {
          if (!other.time_.isEmpty()) {
            if (timeBuilder_.isEmpty()) {
              timeBuilder_.dispose();
              timeBuilder_ = null;
              time_ = other.time_;
              bitField0_ = (bitField0_ & ~0x00000008);
              timeBuilder_ = 
                com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders ?
                   getTimeFieldBuilder() : null;
            } else {
              timeBuilder_.addAllMessages(other.time_);
            }
          }
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasModelName()) {
          
          return false;
        }
        for (int i = 0; i < getPoseCount(); i++) {
          if (!getPose(i).isInitialized()) {
            
            return false;
          }
        }
        for (int i = 0; i < getTimeCount(); i++) {
          if (!getTime(i).isInitialized()) {
            
            return false;
          }
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        gazebo.msgs.GzPoseAnimation.PoseAnimation parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (gazebo.msgs.GzPoseAnimation.PoseAnimation) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      // required string model_name = 1;
      private java.lang.Object modelName_ = "";
      /**
       * <code>required string model_name = 1;</code>
       */
      public boolean hasModelName() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required string model_name = 1;</code>
       */
      public java.lang.String getModelName() {
        java.lang.Object ref = modelName_;
        if (!(ref instanceof java.lang.String)) {
          java.lang.String s = ((com.google.protobuf.ByteString) ref)
              .toStringUtf8();
          modelName_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>required string model_name = 1;</code>
       */
      public com.google.protobuf.ByteString
          getModelNameBytes() {
        java.lang.Object ref = modelName_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          modelName_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>required string model_name = 1;</code>
       */
      public Builder setModelName(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        modelName_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required string model_name = 1;</code>
       */
      public Builder clearModelName() {
        bitField0_ = (bitField0_ & ~0x00000001);
        modelName_ = getDefaultInstance().getModelName();
        onChanged();
        return this;
      }
      /**
       * <code>required string model_name = 1;</code>
       */
      public Builder setModelNameBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        modelName_ = value;
        onChanged();
        return this;
      }

      // optional uint32 model_id = 2;
      private int modelId_ ;
      /**
       * <code>optional uint32 model_id = 2;</code>
       */
      public boolean hasModelId() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>optional uint32 model_id = 2;</code>
       */
      public int getModelId() {
        return modelId_;
      }
      /**
       * <code>optional uint32 model_id = 2;</code>
       */
      public Builder setModelId(int value) {
        bitField0_ |= 0x00000002;
        modelId_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>optional uint32 model_id = 2;</code>
       */
      public Builder clearModelId() {
        bitField0_ = (bitField0_ & ~0x00000002);
        modelId_ = 0;
        onChanged();
        return this;
      }

      // repeated .gazebo.msgs.Pose pose = 3;
      private java.util.List<gazebo.msgs.GzPose.Pose> pose_ =
        java.util.Collections.emptyList();
      private void ensurePoseIsMutable() {
        if (!((bitField0_ & 0x00000004) == 0x00000004)) {
          pose_ = new java.util.ArrayList<gazebo.msgs.GzPose.Pose>(pose_);
          bitField0_ |= 0x00000004;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder> poseBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public java.util.List<gazebo.msgs.GzPose.Pose> getPoseList() {
        if (poseBuilder_ == null) {
          return java.util.Collections.unmodifiableList(pose_);
        } else {
          return poseBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public int getPoseCount() {
        if (poseBuilder_ == null) {
          return pose_.size();
        } else {
          return poseBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public gazebo.msgs.GzPose.Pose getPose(int index) {
        if (poseBuilder_ == null) {
          return pose_.get(index);
        } else {
          return poseBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder setPose(
          int index, gazebo.msgs.GzPose.Pose value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoseIsMutable();
          pose_.set(index, value);
          onChanged();
        } else {
          poseBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder setPose(
          int index, gazebo.msgs.GzPose.Pose.Builder builderForValue) {
        if (poseBuilder_ == null) {
          ensurePoseIsMutable();
          pose_.set(index, builderForValue.build());
          onChanged();
        } else {
          poseBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder addPose(gazebo.msgs.GzPose.Pose value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoseIsMutable();
          pose_.add(value);
          onChanged();
        } else {
          poseBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder addPose(
          int index, gazebo.msgs.GzPose.Pose value) {
        if (poseBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensurePoseIsMutable();
          pose_.add(index, value);
          onChanged();
        } else {
          poseBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder addPose(
          gazebo.msgs.GzPose.Pose.Builder builderForValue) {
        if (poseBuilder_ == null) {
          ensurePoseIsMutable();
          pose_.add(builderForValue.build());
          onChanged();
        } else {
          poseBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder addPose(
          int index, gazebo.msgs.GzPose.Pose.Builder builderForValue) {
        if (poseBuilder_ == null) {
          ensurePoseIsMutable();
          pose_.add(index, builderForValue.build());
          onChanged();
        } else {
          poseBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder addAllPose(
          java.lang.Iterable<? extends gazebo.msgs.GzPose.Pose> values) {
        if (poseBuilder_ == null) {
          ensurePoseIsMutable();
          super.addAll(values, pose_);
          onChanged();
        } else {
          poseBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder clearPose() {
        if (poseBuilder_ == null) {
          pose_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000004);
          onChanged();
        } else {
          poseBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public Builder removePose(int index) {
        if (poseBuilder_ == null) {
          ensurePoseIsMutable();
          pose_.remove(index);
          onChanged();
        } else {
          poseBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public gazebo.msgs.GzPose.Pose.Builder getPoseBuilder(
          int index) {
        return getPoseFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public gazebo.msgs.GzPose.PoseOrBuilder getPoseOrBuilder(
          int index) {
        if (poseBuilder_ == null) {
          return pose_.get(index);  } else {
          return poseBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public java.util.List<? extends gazebo.msgs.GzPose.PoseOrBuilder> 
           getPoseOrBuilderList() {
        if (poseBuilder_ != null) {
          return poseBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(pose_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public gazebo.msgs.GzPose.Pose.Builder addPoseBuilder() {
        return getPoseFieldBuilder().addBuilder(
            gazebo.msgs.GzPose.Pose.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public gazebo.msgs.GzPose.Pose.Builder addPoseBuilder(
          int index) {
        return getPoseFieldBuilder().addBuilder(
            index, gazebo.msgs.GzPose.Pose.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Pose pose = 3;</code>
       */
      public java.util.List<gazebo.msgs.GzPose.Pose.Builder> 
           getPoseBuilderList() {
        return getPoseFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder> 
          getPoseFieldBuilder() {
        if (poseBuilder_ == null) {
          poseBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gazebo.msgs.GzPose.Pose, gazebo.msgs.GzPose.Pose.Builder, gazebo.msgs.GzPose.PoseOrBuilder>(
                  pose_,
                  ((bitField0_ & 0x00000004) == 0x00000004),
                  getParentForChildren(),
                  isClean());
          pose_ = null;
        }
        return poseBuilder_;
      }

      // repeated .gazebo.msgs.Time time = 4;
      private java.util.List<gazebo.msgs.GzTime.Time> time_ =
        java.util.Collections.emptyList();
      private void ensureTimeIsMutable() {
        if (!((bitField0_ & 0x00000008) == 0x00000008)) {
          time_ = new java.util.ArrayList<gazebo.msgs.GzTime.Time>(time_);
          bitField0_ |= 0x00000008;
         }
      }

      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder> timeBuilder_;

      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public java.util.List<gazebo.msgs.GzTime.Time> getTimeList() {
        if (timeBuilder_ == null) {
          return java.util.Collections.unmodifiableList(time_);
        } else {
          return timeBuilder_.getMessageList();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public int getTimeCount() {
        if (timeBuilder_ == null) {
          return time_.size();
        } else {
          return timeBuilder_.getCount();
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public gazebo.msgs.GzTime.Time getTime(int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);
        } else {
          return timeBuilder_.getMessage(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder setTime(
          int index, gazebo.msgs.GzTime.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.set(index, value);
          onChanged();
        } else {
          timeBuilder_.setMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder setTime(
          int index, gazebo.msgs.GzTime.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.set(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.setMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder addTime(gazebo.msgs.GzTime.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(value);
          onChanged();
        } else {
          timeBuilder_.addMessage(value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder addTime(
          int index, gazebo.msgs.GzTime.Time value) {
        if (timeBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          ensureTimeIsMutable();
          time_.add(index, value);
          onChanged();
        } else {
          timeBuilder_.addMessage(index, value);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder addTime(
          gazebo.msgs.GzTime.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder addTime(
          int index, gazebo.msgs.GzTime.Time.Builder builderForValue) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.add(index, builderForValue.build());
          onChanged();
        } else {
          timeBuilder_.addMessage(index, builderForValue.build());
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder addAllTime(
          java.lang.Iterable<? extends gazebo.msgs.GzTime.Time> values) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          super.addAll(values, time_);
          onChanged();
        } else {
          timeBuilder_.addAllMessages(values);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder clearTime() {
        if (timeBuilder_ == null) {
          time_ = java.util.Collections.emptyList();
          bitField0_ = (bitField0_ & ~0x00000008);
          onChanged();
        } else {
          timeBuilder_.clear();
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public Builder removeTime(int index) {
        if (timeBuilder_ == null) {
          ensureTimeIsMutable();
          time_.remove(index);
          onChanged();
        } else {
          timeBuilder_.remove(index);
        }
        return this;
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public gazebo.msgs.GzTime.Time.Builder getTimeBuilder(
          int index) {
        return getTimeFieldBuilder().getBuilder(index);
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public gazebo.msgs.GzTime.TimeOrBuilder getTimeOrBuilder(
          int index) {
        if (timeBuilder_ == null) {
          return time_.get(index);  } else {
          return timeBuilder_.getMessageOrBuilder(index);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public java.util.List<? extends gazebo.msgs.GzTime.TimeOrBuilder> 
           getTimeOrBuilderList() {
        if (timeBuilder_ != null) {
          return timeBuilder_.getMessageOrBuilderList();
        } else {
          return java.util.Collections.unmodifiableList(time_);
        }
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public gazebo.msgs.GzTime.Time.Builder addTimeBuilder() {
        return getTimeFieldBuilder().addBuilder(
            gazebo.msgs.GzTime.Time.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public gazebo.msgs.GzTime.Time.Builder addTimeBuilder(
          int index) {
        return getTimeFieldBuilder().addBuilder(
            index, gazebo.msgs.GzTime.Time.getDefaultInstance());
      }
      /**
       * <code>repeated .gazebo.msgs.Time time = 4;</code>
       */
      public java.util.List<gazebo.msgs.GzTime.Time.Builder> 
           getTimeBuilderList() {
        return getTimeFieldBuilder().getBuilderList();
      }
      private com.google.protobuf.RepeatedFieldBuilder<
          gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder> 
          getTimeFieldBuilder() {
        if (timeBuilder_ == null) {
          timeBuilder_ = new com.google.protobuf.RepeatedFieldBuilder<
              gazebo.msgs.GzTime.Time, gazebo.msgs.GzTime.Time.Builder, gazebo.msgs.GzTime.TimeOrBuilder>(
                  time_,
                  ((bitField0_ & 0x00000008) == 0x00000008),
                  getParentForChildren(),
                  isClean());
          time_ = null;
        }
        return timeBuilder_;
      }

      // @@protoc_insertion_point(builder_scope:gazebo.msgs.PoseAnimation)
    }

    static {
      defaultInstance = new PoseAnimation(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:gazebo.msgs.PoseAnimation)
  }

  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_gazebo_msgs_PoseAnimation_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_gazebo_msgs_PoseAnimation_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\024pose_animation.proto\022\013gazebo.msgs\032\npos" +
      "e.proto\032\ntime.proto\"w\n\rPoseAnimation\022\022\n\n" +
      "model_name\030\001 \002(\t\022\020\n\010model_id\030\002 \001(\r\022\037\n\004po" +
      "se\030\003 \003(\0132\021.gazebo.msgs.Pose\022\037\n\004time\030\004 \003(" +
      "\0132\021.gazebo.msgs.TimeB\021B\017GzPoseAnimation"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_gazebo_msgs_PoseAnimation_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_gazebo_msgs_PoseAnimation_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_gazebo_msgs_PoseAnimation_descriptor,
              new java.lang.String[] { "ModelName", "ModelId", "Pose", "Time", });
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          gazebo.msgs.GzPose.getDescriptor(),
          gazebo.msgs.GzTime.getDescriptor(),
        }, assigner);
  }

  // @@protoc_insertion_point(outer_class_scope)
}
